/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:01:03 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/DDLogFileManager.h>

@class NSString;

@interface DDLogFileManagerDefault : NSObject <DDLogFileManager> {

	unsigned long long maximumNumberOfLogFiles;
	NSString* _logsDirectory;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign) unsigned long long maximumNumberOfLogFiles; 
-(id)initWithLogsDirectory:(id)arg1 ;
-(id)defaultLogsDirectory;
-(id)sortedLogFileInfos;
-(unsigned long long)maximumNumberOfLogFiles;
-(id)logsDirectory;
-(BOOL)isLogFile:(id)arg1 ;
-(id)unsortedLogFilePaths;
-(id)unsortedLogFileInfos;
-(id)generateShortUUID;
-(id)unsortedLogFileNames;
-(id)sortedLogFilePaths;
-(id)sortedLogFileNames;
-(id)createNewLogFile;
-(void)setMaximumNumberOfLogFiles:(unsigned long long)arg1 ;
-(void)dealloc;
-(id)init;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)deleteOldLogFiles;
@end

