/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:51 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate, FBActivitySensorDataCollectionConfig;

@interface FBActivitySession : NSObject {

	NSDate* _dataStartDate;
	FBActivitySensorDataCollectionConfig* _sensorDataCollectionConfig;

}

@property (nonatomic,readonly) NSDate * dataStartDate;                                                         //@synthesize dataStartDate=_dataStartDate - In the implementation block
@property (nonatomic,readonly) FBActivitySensorDataCollectionConfig * sensorDataCollectionConfig;              //@synthesize sensorDataCollectionConfig=_sensorDataCollectionConfig - In the implementation block
-(id)initWithStartDate:(id)arg1 sensorDataCollectionConfig:(id)arg2 ;
-(NSDate *)dataStartDate;
-(FBActivitySensorDataCollectionConfig *)sensorDataCollectionConfig;
@end

