/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:41 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBAccountRecoveryUIProviding <NSObject>
@required
-(id)spinnerViewControllerWithLabelText:(id)arg1;
-(id)searchViewControllerWithFlowData:(id)arg1 searchController:(id)arg2 searchFlowControlling:(id)arg3;
-(id)contactPointsViewControllerWithFlowData:(id)arg1 codeEntryController:(id)arg2 contactPointsFlowControlling:(id)arg3;
-(id)codeEntryViewControllerWithFlowData:(id)arg1 codeEntryController:(id)arg2 codeEntryFlowControlling:(id)arg3;
-(id)otherSessionsViewController:(id)arg1;
-(id)changePasswordViewControllerWithFlowData:(id)arg1 changePasswordController:(id)arg2 changePasswordFlowControlling:(id)arg3;
-(id)friendViewController:(id)arg1;
-(id)fdrViewControllerWithFlowData:(id)arg1 fdrFlowControlling:(id)arg2;

@end

