/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:35 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBAdInterfacesPromotion, NSArray, NSSet, FBAdInterfacesBudget;

@interface FBAdInterfacesEditPromotionResponseBuilder : NSObject {

	FBAdInterfacesPromotion* _promotion;
	NSArray* _budgetRecommendations;
	NSSet* _editedFields;
	FBAdInterfacesBudget* _defaultBudget;

}
+(id)adInterfacesEditPromotionResponse;
+(id)adInterfacesEditPromotionResponseFromExistingAdInterfacesEditPromotionResponse:(id)arg1 ;
-(id)withPromotion:(id)arg1 ;
-(id)withEditedFields:(id)arg1 ;
-(id)withBudgetRecommendations:(id)arg1 ;
-(id)withDefaultBudget:(id)arg1 ;
-(id)build;
@end

