/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:41 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <Facebook/FBWebViewControllerDelegate.h>
#import <Facebook/FBPaymentsEventAnnouncing.h>

@protocol FBAdPaymentsPayPalViewControllerDelegate;
@class FBUserSession, NSString, FBWebViewController, FBPaymentsEventListenerAnnouncer;

@interface FBAdPaymentsPayPalViewController : UIViewController <FBWebViewControllerDelegate, FBPaymentsEventAnnouncing> {

	FBUserSession* _session;
	NSString* _paymentAccountId;
	FBWebViewController* _webViewController;
	FBPaymentsEventListenerAnnouncer* _eventAnnouncer;
	BOOL _isViewFirstPresent;
	BOOL _isPayPalViewControllerCancelled;
	id<FBAdPaymentsPayPalViewControllerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<FBAdPaymentsPayPalViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)announcerIdentifier;
-(void)addEventListener:(id)arg1 ;
-(void)removeEventListener:(id)arg1 ;
-(BOOL)webViewController:(id)arg1 shouldStartLoadURL:(id)arg2 navigationType:(long long)arg3 ;
-(void)_didCancelBarButtonItemClicked:(id)arg1 ;
-(id)initWithSession:(id)arg1 paymentAccountId:(id)arg2 ;
-(void)_loadPayPalWebView;
-(void)_didCancelAddPayPalViewController;
-(void)_updateNavigationBarItems;
-(void)setDelegate:(id<FBAdPaymentsPayPalViewControllerDelegate>)arg1 ;
-(id<FBAdPaymentsPayPalViewControllerDelegate>)delegate;
-(void)viewWillLayoutSubviews;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
@end

