/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:35 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray, FBAdInterfacesAudienceOption, NSDictionary;

@interface FBAdInterfacesPromotionInfoBuilder : NSObject {

	NSArray* _accounts;
	NSArray* _budgetRecommendations;
	FBAdInterfacesAudienceOption* _defaultAudienceOption;
	NSDictionary* _lastUsedTargeting;

}
+(id)anAdInterfacesPromotionInfo;
+(id)anAdInterfacesPromotionInfoFromExistingAdInterfacesPromotionInfo:(id)arg1 ;
-(id)withAccounts:(id)arg1 ;
-(id)withBudgetRecommendations:(id)arg1 ;
-(id)withDefaultAudienceOption:(id)arg1 ;
-(id)withLastUsedTargeting:(id)arg1 ;
-(id)build;
@end

