/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:35 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBAdInterfacesDisplayableLocation, NSError;

@interface FBAdInterfacesMapPickerComponentStateBuilder : NSObject {

	FBAdInterfacesDisplayableLocation* _selectedLocation;
	BOOL _loadingGeocoding;
	BOOL _loadingPopulationEstimation;
	long long _estimatedPopulation;
	BOOL _showCustomAddress;
	NSError* _geocodingError;

}
+(id)adInterfacesMapPickerComponentStateFromExistingAdInterfacesMapPickerComponentState:(id)arg1 ;
+(id)adInterfacesMapPickerComponentState;
-(id)withSelectedLocation:(id)arg1 ;
-(id)withLoadingGeocoding:(BOOL)arg1 ;
-(id)withGeocodingError:(id)arg1 ;
-(id)withShowCustomAddress:(BOOL)arg1 ;
-(id)withLoadingPopulationEstimation:(BOOL)arg1 ;
-(id)withEstimatedPopulation:(long long)arg1 ;
-(id)build;
@end

