/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:44 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBGraphQLConnectionStoreSimpleDeleteController.h>

@class FBUserSession, NSMapTable, NSMutableArray, FBAlbumStoreManagerListenerAnnouncer, FBAlbumStoreEdgeHandler, NSString;

@interface FBAlbumStoreManager : NSObject <FBGraphQLConnectionStoreSimpleDeleteController> {

	FBUserSession* _session;
	NSMapTable* _storeMap;
	NSMutableArray* _deletedFilters;
	FBAlbumStoreManagerListenerAnnouncer* _announcer;
	FBAlbumStoreEdgeHandler* _edgeHandler;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)albumStoreWithRequestProvider:(id)arg1 networkRequestThresholdInSeconds:(int)arg2 alwaysUseFirstCachedResponse:(BOOL)arg3 initialAlbums:(id)arg4 ;
-(void)deleteAlbumsWithIDs:(id)arg1 ;
-(void)_applyDeleteFilters;
-(id)_edgeStoreWithInitialNodes:(id)arg1 requestProvider:(id)arg2 ;
-(id)_allDeletedAlbumIds;
-(void)graphQLConnectionStoreSimple:(id)arg1 deleteNodesWithGraphQLIDs:(id)arg2 ;
-(id)initWithSession:(id)arg1 ;
-(void)removeListener:(id)arg1 ;
-(void)addListener:(id)arg1 ;
@end

