/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:44 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/ASDisplayNode.h>
#import <Facebook/FBMapNodeDelegate.h>

@protocol FBAnnotationUnderlayNodeDelegate;
@class FBTextAnnotationController, FBAnnotationLayout, FBRichStoryBlockDisplayContext, FBRichStoryBlockControllerRegistry, FBRichStoryAnnotationBlock, FBMapNode, ASControlNode, NSString;

@interface FBAnnotationUnderlayNode : ASDisplayNode <FBMapNodeDelegate> {

	FBTextAnnotationController* _closeButtonController;
	FBAnnotationLayout* _layout;
	FBRichStoryBlockDisplayContext* _displayContext;
	FBRichStoryBlockControllerRegistry* _controllerRegistry;
	FBRichStoryAnnotationBlock* _closeAnnotation;
	id<FBAnnotationUnderlayNodeDelegate> _delegate;
	FBMapNode* _mapNode;

}

@property (nonatomic,readonly) ASControlNode * closeButtonNode; 
@property (assign,nonatomic,__weak) id<FBAnnotationUnderlayNodeDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) FBMapNode * mapNode;                                             //@synthesize mapNode=_mapNode - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)containsUnderlayAnnotations:(id)arg1 ;
-(void)_staticInitialize;
-(id)_annotations;
-(void)didTapClose;
-(CGSize)calculateSizeThatFits:(CGSize)arg1 ;
-(id)initWithAnnotationNodes:(id)arg1 session:(id)arg2 displayContext:(id)arg3 ;
-(FBMapNode *)mapNode;
-(void)didTapMapNode:(id)arg1 ;
-(ASControlNode *)closeButtonNode;
-(void)setDelegate:(id<FBAnnotationUnderlayNodeDelegate>)arg1 ;
-(id<FBAnnotationUnderlayNodeDelegate>)delegate;
-(void)layout;
@end

