/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:38 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>
#import <Facebook/FIGCardContentHScrollChildCompliant.h>

@protocol FBQueriedNodeFieldsProtocolFBTimelineAppCollectionEntityProtocol;
@class NSURL, NSArray, NSString, FBMemStoryAttachment, FBFeedToolbox, FBMemModelObject;

@interface FBArticleChainingFeedUnitArticleComponent : CKCompositeComponent <FIGCardContentHScrollChildCompliant> {

	NSURL* _navigationURL;
	CKTypedComponentAction<> _xoutAction;
	NSArray* _trackingCodes;
	NSString* _storyId;
	FBMemStoryAttachment* _article;
	FBFeedToolbox* _toolbox;
	FBMemModelObject*<FBQueriedNodeFieldsProtocol>*<FBTimelineAppCollectionEntityProtocol> _entity;
	NSString* _source;
	CKTypedComponentAction<FBMemStoryAttachment *> _didTapArticle;

}

@property (nonatomic,copy,readonly) NSString * source;                                                    //@synthesize source=_source - In the implementation block
@property (nonatomic,readonly) CKTypedComponentAction<FBMemStoryAttachment *> didTapArticle;              //@synthesize didTapArticle=_didTapArticle - In the implementation block
@property (nonatomic,copy,readonly) FBMemStoryAttachment * article;                                       //@synthesize article=_article - In the implementation block
@property (nonatomic,readonly) FBFeedToolbox * toolbox;                                                   //@synthesize toolbox=_toolbox - In the implementation block
@property (nonatomic,copy,readonly) NSArray * trackingCodes;                                              //@synthesize trackingCodes=_trackingCodes - In the implementation block
+(id)newWithUnit:(id)arg1 storyId:(id)arg2 xoutAction:(CKTypedComponentAction<>)arg3 source:(id)arg4 options:(FBArticleChainingFeedUnitArticleOptions)arg5 toolbox:(id)arg6 ;
-(FBFeedToolbox *)toolbox;
-(void)becameFullyVisible;
-(NSArray *)trackingCodes;
-(void)didTapShare:(id)arg1 ;
-(void)didTapSave:(id)arg1 ;
-(FBMemStoryAttachment *)article;
-(CKTypedComponentAction<FBMemStoryAttachment *>)didTapArticle;
-(NSString *)source;
@end

