/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:42 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBAvatarWithSecondaryActionsTableViewCell_DEPRECATED.h>

@class FBFeedbackReactionDataProvider, UIImageView;

@interface FBAvatarWithReactionTableViewCell : FBAvatarWithSecondaryActionsTableViewCell_DEPRECATED {

	FBFeedbackReactionDataProvider* _reactionDataProvider;
	UIImageView* _reactionIconView;
	long long _reactionKey;

}

@property (assign,nonatomic) long long reactionKey;              //@synthesize reactionKey=_reactionKey - In the implementation block
-(void)setReactionKey:(long long)arg1 ;
-(id)initWithReuseIdentifier:(id)arg1 profilePictureSize:(unsigned long long)arg2 reactionDataProvider:(id)arg3 session:(id)arg4 ;
-(long long)reactionKey;
-(void)layoutSubviews;
-(void)prepareForReuse;
@end

