/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:45 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSArray;

@interface FBAvatarsWithSectionName : NSObject {

	NSString* _sectionName;
	NSArray* _avatars;

}

@property (nonatomic,copy,readonly) NSString * sectionName;              //@synthesize sectionName=_sectionName - In the implementation block
@property (nonatomic,copy,readonly) NSArray * avatars;                   //@synthesize avatars=_avatars - In the implementation block
-(NSArray *)avatars;
-(id)initWithAvatars:(id)arg1 sectionName:(id)arg2 ;
-(NSString *)sectionName;
@end

