/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:39 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@protocol FBBackstageConsumptionProtocol, FBWebImageSpecifier;
@class FBWebImageView;

@interface FBBackstageTransitionSnapshotView : UIView {

	FBWebImageView* _imageView1;
	FBWebImageView* _imageView2;
	id<FBBackstageConsumptionProtocol> _originalItem;
	id<FBWebImageSpecifier> _thumbnailItemSpecifier;
	id<FBWebImageSpecifier> _animatingItemSpecifier;

}

@property (nonatomic,retain) id<FBWebImageSpecifier> thumbnailItemSpecifier;              //@synthesize thumbnailItemSpecifier=_thumbnailItemSpecifier - In the implementation block
@property (nonatomic,retain) id<FBWebImageSpecifier> animatingItemSpecifier;              //@synthesize animatingItemSpecifier=_animatingItemSpecifier - In the implementation block
-(void)setThumbnailItemSpecifier:(id<FBWebImageSpecifier>)arg1 ;
-(void)transitionToDestination:(unsigned long long)arg1 animated:(BOOL)arg2 ;
-(void)setAnimatingItemSpecifier:(id<FBWebImageSpecifier>)arg1 ;
-(id<FBWebImageSpecifier>)thumbnailItemSpecifier;
-(id<FBWebImageSpecifier>)animatingItemSpecifier;
-(void)layoutSubviews;
-(id)initWithSession:(id)arg1 ;
@end

