/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:42 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface FBBackgroundEventKey : FBValueObject <NSCopying> {

	unsigned long long _eventType;
	NSString* _eventIdentifier;

}

@property (nonatomic,readonly) unsigned long long eventType;                 //@synthesize eventType=_eventType - In the implementation block
@property (nonatomic,copy,readonly) NSString * eventIdentifier;              //@synthesize eventIdentifier=_eventIdentifier - In the implementation block
-(unsigned long)hashDynamic;
-(BOOL)isEqualDynamic:(id)arg1 ;
-(id)initWithEventType:(unsigned long long)arg1 eventIdentifier:(id)arg2 ;
-(unsigned long long)eventType;
-(NSString *)eventIdentifier;
@end

