/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:39 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBBackstageOptimisticFactory : NSObject
+(id)addPostsFromTask:(id)arg1 toThread:(id)arg2 updateType:(unsigned long long)arg3 ;
+(id)updateThread:(/*^block*/id)arg1 matchingGraphQLID:(id)arg2 inPerson:(id)arg3 ;
+(id)updateThread:(id)arg1 inPerson:(id)arg2 ;
+(id)appendThread:(id)arg1 inPerson:(id)arg2 ;
+(id)updatePost:(id)arg1 inThread:(id)arg2 ;
+(id)updateSeenForThread:(id)arg1 ;
@end

