/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:40 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBBookmarksRowTableViewCellProtocol <NSObject>
@required
+(double)height;
-(void)setStyle:(unsigned long long)arg1 text:(id)arg2 subtitleText:(id)arg3 unreadText:(id)arg4 detailTextType:(unsigned long long)arg5 image:(id)arg6 postNameIcon:(id)arg7 imageDownloader:(id)arg8 staticImage:(id)arg9 hasImageBorder:(BOOL)arg10 roundingStyle:(unsigned long long)arg11 cardStyle:(unsigned long long)arg12 isFirstCell:(BOOL)arg13 isLastCell:(BOOL)arg14 isDeepLinkItem:(BOOL)arg15 accessoryType:(long long)arg16 separatorInset:(UIEdgeInsets)arg17 dividerColor:(id)arg18;
-(void)setDividerColor:(id)arg1;

@end

