/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:55 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Facebook/Facebook-Structs.h>
@class AVAssetWriter, AVAssetWriterInput, AVAssetWriterInputPixelBufferAdaptor, NSDate, UIImage, NSTimer, NSURL;

@interface FBBugReportVideoScreenRecorder : NSObject {

	AVAssetWriter* _writer;
	AVAssetWriterInput* _writerInput;
	AVAssetWriterInputPixelBufferAdaptor* _writerInputPixelBufferAdaptor;
	NSDate* _startTime;
	UIImage* _latestScreenshot;
	NSTimer* _timer;
	BOOL _captureFrameInProgress;
	NSURL* _originalFilenameURL;
	NSURL* _tmpFilenameURL;
	CGSize _frameSize;

}
-(void)captureFrame:(id)arg1 ;
-(void)captureFrameInternal;
-(id)imageRotatedByDegrees:(id)arg1 radians:(double)arg2 ;
-(void)stopRecording;
-(BOOL)startRecording:(id)arg1 ;
@end

