/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:46 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <UIKit/UIView.h>

@class UIView;

@interface FBCarouselFooterContainerView : UIView {

	UIView* _contentView;
	double _visibilityPercentage;

}

@property (nonatomic,retain) UIView * contentView;                     //@synthesize contentView=_contentView - In the implementation block
@property (assign,nonatomic) double visibilityPercentage;              //@synthesize visibilityPercentage=_visibilityPercentage - In the implementation block
-(void)setVisibilityPercentage:(double)arg1 ;
-(double)visibilityPercentage;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)layoutSubviews;
-(UIView *)contentView;
-(void)setContentView:(UIView *)arg1 ;
-(id)initWithContentView:(id)arg1 ;
@end

