/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:46 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/CKCompositeComponent.h>

@interface FBCameraComponent : CKCompositeComponent
+(id)newWithModel:(id)arg1 buttonsComponent:(id)arg2 backgroundComponent:(id)arg3 captureManager:(id)arg4 appearanceProvider:(id)arg5 viewFinderAnnouncer:(id)arg6 viewFinderTapEvent:(id)arg7 viewFinderDoubleTapEvent:(id)arg8 pinchEvent:(id)arg9 previewWillAppearEvent:(id)arg10 previewWillDisappearEvent:(id)arg11 flashAnnouncer:(id)arg12 startupDestinationManager:(id)arg13 ;
@end

