/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:46 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBCKGraphQLQueryFactory : NSObject
+(id)liveCommentsQueryForInput:(id)arg1 topLevelCommentParameters:(id)arg2 ;
+(id)_initialLoadQueryForFeedbackID:(id)arg1 commentOrder:(unsigned long long)arg2 count:(unsigned long long)arg3 fetchAvailableCommentOrderings:(BOOL)arg4 fetchFriendResharers:(BOOL)arg5 fetchResharePreviews:(BOOL)arg6 accurateShareCountUnderEqualTo:(unsigned long long)arg7 topLevelCommentParameters:(id)arg8 ;
+(id)_initialLoadQueryForRankedFocusedCommentID:(id)arg1 feedbackID:(id)arg2 count:(unsigned long long)arg3 isHighQuality:(BOOL)arg4 accurateShareCountUnderEqualTo:(unsigned long long)arg5 topLevelCommentParameters:(id)arg6 ;
+(id)_initialLoadQueryForUnrankedFocusedCommentID:(id)arg1 commentOrder:(unsigned long long)arg2 countCommentsMoreRecentThanFocusedComment:(unsigned long long)arg3 feedbackID:(id)arg4 count:(unsigned long long)arg5 accurateShareCountUnderEqualTo:(unsigned long long)arg6 topLevelCommentParameters:(id)arg7 ;
+(id)initialLoadQueryForFeedbackID:(id)arg1 focusedCommentID:(id)arg2 commentOrder:(unsigned long long)arg3 count:(unsigned long long)arg4 fetchAvailableCommentOrderings:(BOOL)arg5 fetchFriendResharers:(BOOL)arg6 fetchResharePreviews:(BOOL)arg7 accurateShareCountUnderEqualTo:(unsigned long long)arg8 topLevelCommentParameters:(id)arg9 ;
+(id)headLoadQueryForFeedbackID:(id)arg1 commentOrder:(unsigned long long)arg2 upToCursor:(id)arg3 count:(unsigned long long)arg4 accurateShareCountUnderEqualTo:(unsigned long long)arg5 topLevelCommentParameters:(id)arg6 ;
+(id)tailLoadQueryForFeedbackID:(id)arg1 commentOrder:(unsigned long long)arg2 afterCursor:(id)arg3 count:(unsigned long long)arg4 accurateShareCountUnderEqualTo:(unsigned long long)arg5 topLevelCommentParameters:(id)arg6 ;
+(id)neckLoadQueryForFeedbackID:(id)arg1 commentOrder:(unsigned long long)arg2 afterCursor:(id)arg3 count:(unsigned long long)arg4 accurateShareCountUnderEqualTo:(unsigned long long)arg5 topLevelCommentParameters:(id)arg6 ;
+(id)commentsRefreshQueryWithIDs:(id)arg1 topLevelCommentParameters:(id)arg2 ;
+(id)commentRefreshQueryWithLegacyID:(id)arg1 topLevelCommentParameters:(id)arg2 ;
+(id)commentVideoStatusQueryWithLegacyID:(id)arg1 ;
@end

