/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:46 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSNumber;

@interface FBCKQueryTopLevelCommentParameters : FBValueObject <NSCopying> {

	BOOL _loadFullReplyPreviews;
	NSString* _enableMostRecentCommentReplyPreview;
	NSString* _feedbackIncludeReactionsForComment;
	NSString* _feedbackIncludeReactionsOnCommentAuthor;
	NSNumber* _mostRecentReplyPreviewCount;
	NSString* _shouldFetchCommentInteractors;
	NSString* _shouldFetchFriendCommenters;
	NSString* _shouldFetchInterestingRepliers;
	NSString* _useDefaultActor;

}

@property (nonatomic,copy,readonly) NSString * enableMostRecentCommentReplyPreview;                  //@synthesize enableMostRecentCommentReplyPreview=_enableMostRecentCommentReplyPreview - In the implementation block
@property (nonatomic,copy,readonly) NSString * feedbackIncludeReactionsForComment;                   //@synthesize feedbackIncludeReactionsForComment=_feedbackIncludeReactionsForComment - In the implementation block
@property (nonatomic,copy,readonly) NSString * feedbackIncludeReactionsOnCommentAuthor;              //@synthesize feedbackIncludeReactionsOnCommentAuthor=_feedbackIncludeReactionsOnCommentAuthor - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * mostRecentReplyPreviewCount;                          //@synthesize mostRecentReplyPreviewCount=_mostRecentReplyPreviewCount - In the implementation block
@property (nonatomic,copy,readonly) NSString * shouldFetchCommentInteractors;                        //@synthesize shouldFetchCommentInteractors=_shouldFetchCommentInteractors - In the implementation block
@property (nonatomic,copy,readonly) NSString * shouldFetchFriendCommenters;                          //@synthesize shouldFetchFriendCommenters=_shouldFetchFriendCommenters - In the implementation block
@property (nonatomic,copy,readonly) NSString * shouldFetchInterestingRepliers;                       //@synthesize shouldFetchInterestingRepliers=_shouldFetchInterestingRepliers - In the implementation block
@property (nonatomic,copy,readonly) NSString * useDefaultActor;                                      //@synthesize useDefaultActor=_useDefaultActor - In the implementation block
@property (nonatomic,readonly) BOOL loadFullReplyPreviews;                                           //@synthesize loadFullReplyPreviews=_loadFullReplyPreviews - In the implementation block
-(NSString *)shouldFetchCommentInteractors;
-(NSString *)shouldFetchFriendCommenters;
-(NSString *)shouldFetchInterestingRepliers;
-(NSString *)feedbackIncludeReactionsOnCommentAuthor;
-(NSString *)feedbackIncludeReactionsForComment;
-(id)initWithEnableMostRecentCommentReplyPreview:(id)arg1 feedbackIncludeReactionsForComment:(id)arg2 feedbackIncludeReactionsOnCommentAuthor:(id)arg3 mostRecentReplyPreviewCount:(id)arg4 shouldFetchCommentInteractors:(id)arg5 shouldFetchFriendCommenters:(id)arg6 shouldFetchInterestingRepliers:(id)arg7 useDefaultActor:(id)arg8 loadFullReplyPreviews:(BOOL)arg9 ;
-(NSString *)enableMostRecentCommentReplyPreview;
-(NSNumber *)mostRecentReplyPreviewCount;
-(NSString *)useDefaultActor;
-(BOOL)loadFullReplyPreviews;
@end

