/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:50 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>

@class FBComposerSprout;

@interface FBComposerSproutComponent : CKCompositeComponent {

	FBComposerSprout* _sprout;
	CKTypedComponentAction<> _tapAction;

}
+(id)newWithSprout:(id)arg1 tapAction:(CKTypedComponentAction<>)arg2 style:(id)arg3 bottomComponent:(id)arg4 attributes:(const unordered_map<CKComponentViewAttribute, CKBoxedValue, std::__1::hash<CKComponentViewAttribute>, std::__1::equal_to<CKComponentViewAttribute>, std::__1::allocator<std::__1::pair<const CKComponentViewAttribute, CKBoxedValue> > >*)arg5 options:(const FBComposerSproutOptions*)arg6 ;
-(void)didTapSprout;
@end

