/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:36 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UIImage, FBComposerPublication, FBPublicationError, NSDate, NSDictionary;

@interface FBComposerPublicationStatusEventRecord : NSObject {

	int _mediaItemType;
	unsigned long long _eventType;
	UIImage* _mediaItemThumbnail;
	FBComposerPublication* _composerPublication;
	FBPublicationError* _publicationError;
	double _publishingProgress;
	NSDate* _scheduledPublishingDate;
	NSDictionary* _uploadQualityByMediaID;

}

@property (nonatomic,readonly) unsigned long long eventType;                             //@synthesize eventType=_eventType - In the implementation block
@property (nonatomic,readonly) UIImage * mediaItemThumbnail;                             //@synthesize mediaItemThumbnail=_mediaItemThumbnail - In the implementation block
@property (nonatomic,readonly) int mediaItemType;                                        //@synthesize mediaItemType=_mediaItemType - In the implementation block
@property (nonatomic,readonly) FBComposerPublication * composerPublication;              //@synthesize composerPublication=_composerPublication - In the implementation block
@property (nonatomic,readonly) FBPublicationError * publicationError;                    //@synthesize publicationError=_publicationError - In the implementation block
@property (nonatomic,readonly) double publishingProgress;                                //@synthesize publishingProgress=_publishingProgress - In the implementation block
@property (nonatomic,copy,readonly) NSDate * scheduledPublishingDate;                    //@synthesize scheduledPublishingDate=_scheduledPublishingDate - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * uploadQualityByMediaID;               //@synthesize uploadQualityByMediaID=_uploadQualityByMediaID - In the implementation block
-(id)initWithEventType:(unsigned long long)arg1 composerPublication:(id)arg2 publicationError:(id)arg3 scheduledPublishingDate:(id)arg4 publishingProgress:(double)arg5 mediaItemType:(int)arg6 mediaItemThumbnail:(id)arg7 uploadQualityByMediaID:(id)arg8 ;
-(UIImage *)mediaItemThumbnail;
-(FBComposerPublication *)composerPublication;
-(FBPublicationError *)publicationError;
-(double)publishingProgress;
-(NSDate *)scheduledPublishingDate;
-(NSDictionary *)uploadQualityByMediaID;
-(id)description;
-(int)mediaItemType;
-(unsigned long long)eventType;
@end

