/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:01:01 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSDictionary, NSString;

@interface FBComposerLiteOpenGraphContent : FBValueObject <NSCopying> {

	NSDictionary* _actionProperties;
	NSString* _actionType;
	NSString* _previewPropertyName;

}

@property (nonatomic,copy,readonly) NSDictionary * actionProperties;              //@synthesize actionProperties=_actionProperties - In the implementation block
@property (nonatomic,copy,readonly) NSString * actionType;                        //@synthesize actionType=_actionType - In the implementation block
@property (nonatomic,copy,readonly) NSString * previewPropertyName;               //@synthesize previewPropertyName=_previewPropertyName - In the implementation block
-(NSString *)previewPropertyName;
-(id)initWithActionProperties:(id)arg1 actionType:(id)arg2 previewPropertyName:(id)arg3 ;
-(NSDictionary *)actionProperties;
-(NSString *)actionType;
@end

