/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:46 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/FBComposerPhotoOverlayView.h>
#import <Facebook/FBComposerPhotoOverlayViewProtocol.h>

@class UIImageView, FBMStickerView, NSNumber, NSString;

@interface FBComposerStickerView : FBComposerPhotoOverlayView <FBComposerPhotoOverlayViewProtocol> {

	UIImageView* _imageProvidedStickerView;
	FBMStickerView* _stickerView;
	NSNumber* _stickerID;

}

@property (assign,nonatomic) BOOL selected; 
@property (nonatomic,copy) NSNumber * stickerID;                    //@synthesize stickerID=_stickerID - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSNumber *)stickerID;
-(void)setStickerID:(NSNumber *)arg1 ;
-(Class)photoOverlayAttachmentGestureHandlerClass;
-(void)_commonSetUpWithStickerID:(id)arg1 ;
-(void)_removeStickersViewGestures;
-(id)getCurrentStickerImage;
-(id)initWithStickerImage:(id)arg1 stickerID:(id)arg2 ;
-(id)initWithStickerView:(id)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id)contentView;
-(id)accessibilityIdentifier;
-(void)setSelected:(BOOL)arg1 ;
-(BOOL)isAccessibilityElement;
@end

