/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:31 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBComposerPresentationHandler <NSObject>
@required
-(void)presentModalViewController:(id)arg1 fromViewController:(id)arg2 options:(unsigned long long)arg3 animated:(BOOL)arg4 completionHandler:(/*^block*/id)arg5;
-(void)presentPopoverOverlayViewController:(id)arg1 popoverInfo:(id)arg2 options:(unsigned long long)arg3 animated:(BOOL)arg4 completionHandler:(/*^block*/id)arg5;
-(void)dismissViewController:(id)arg1 animated:(BOOL)arg2 completionHandler:(/*^block*/id)arg3;

@end

