/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:39 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/FBCompositeSectionComponent.h>

@interface FBComposerExpressionPickerSectionSingleModelSectionComponent : FBCompositeSectionComponent
+(id)newWithQuery:(id)arg1 searchText:(id)arg2 sectionComponentBlock:(/*^block*/id)arg3 configuration:(SCD_Struct_FB302)arg4 toolbox:(id)arg5 ;
@end

