/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>

@class FBMemComment;

@interface FBCommentStreamAccessibleCommentWithTimestampHeaderUFIComponent : CKCompositeComponent {

	CKTypedComponentAction<> _replyButtonAction;
	CKTypedComponentAction<> _moreButtonAction;
	FBMemComment* _comment;

}
+(id)newWithComment:(id)arg1 likeButtonAction:(CKTypedComponentAction<>)arg2 replyButtonAction:(CKTypedComponentAction<>)arg3 moreButtonAction:(CKTypedComponentAction<>)arg4 showExtraActions:(BOOL)arg5 theme:(unsigned long long)arg6 toolbox:(id)arg7 ;
-(void)replyButtonTapped:(id)arg1 withParentGraphQLID:(id)arg2 ;
-(void)moreButtonTapped:(id)arg1 ;
@end

