/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:45 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <UIKit/UIView.h>

@class FBCropContainerView, FBCropBottomBar, FBMediaTopNavigationBar, FBCropOptionsBarView;

@interface FBCropView : UIView {

	FBCropContainerView* _cropContainerView;
	FBCropBottomBar* _cropBottomBar;
	FBMediaTopNavigationBar* _cropTopBar;
	BOOL _cropOptionsBarViewHidden;
	FBCropOptionsBarView* _cropOptionsBarView;
	double _topLayoutGuideLength;
	long long _interfaceOrientation;

}

@property (nonatomic,readonly) FBCropContainerView * cropContainerView;              //@synthesize cropContainerView=_cropContainerView - In the implementation block
@property (nonatomic,readonly) FBCropBottomBar * cropBottomBar;                      //@synthesize cropBottomBar=_cropBottomBar - In the implementation block
@property (nonatomic,readonly) FBMediaTopNavigationBar * cropTopBar;                 //@synthesize cropTopBar=_cropTopBar - In the implementation block
@property (nonatomic,retain) FBCropOptionsBarView * cropOptionsBarView;              //@synthesize cropOptionsBarView=_cropOptionsBarView - In the implementation block
@property (assign,nonatomic) double topLayoutGuideLength;                            //@synthesize topLayoutGuideLength=_topLayoutGuideLength - In the implementation block
@property (assign,nonatomic) long long interfaceOrientation;                         //@synthesize interfaceOrientation=_interfaceOrientation - In the implementation block
-(void)setTopLayoutGuideLength:(double)arg1 ;
-(double)topLayoutGuideLength;
-(FBMediaTopNavigationBar *)cropTopBar;
-(CGRect)_cropContainerFrameForBounds:(CGRect)arg1 topBarHeight:(double)arg2 bottomBarHeight:(double)arg3 ;
-(CGRect)_cropOptionsBarViewFrame;
-(CGRect)_cropTopBarFrameForBounds:(CGRect)arg1 ;
-(CGRect)_cropBottomBarFrameForBounds:(CGRect)arg1 ;
-(void)setCropOptionsBarView:(FBCropOptionsBarView *)arg1 ;
-(FBCropBottomBar *)cropBottomBar;
-(FBCropOptionsBarView *)cropOptionsBarView;
-(id)initWithFrame:(CGRect)arg1 image:(id)arg2 photoCropInfo:(id)arg3 interfaceOrientation:(long long)arg4 userManipulableCropbox:(BOOL)arg5 shouldDrawInnerGrid:(BOOL)arg6 showTopBar:(BOOL)arg7 mediaPickerStyle:(unsigned long long)arg8 ;
-(FBCropContainerView *)cropContainerView;
-(void)setCropOptionsBarHidden:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)layoutSubviews;
-(long long)interfaceOrientation;
-(void)setInterfaceOrientation:(long long)arg1 ;
@end

