/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:50 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <UIKit/UITableViewController.h>

@protocol FBDBLSettingsCallbackProtocol;
@class FBDBLSettingsMainHeaderView, FBDeviceBasedAccount, FBImageDownloader;

@interface FBDBLSettingsMainViewController : UITableViewController {

	FBDBLSettingsMainMetrics* _metrics;
	FBDBLSettingsMainHeaderView* _settingsMainHeaderView;
	FBDeviceBasedAccount* _userAccount;
	FBImageDownloader* _imageDownloader;
	id<FBDBLSettingsCallbackProtocol> _settingsCallback;

}
-(id)_makeTableHeaderView;
-(unsigned long long)_getButtonType:(id)arg1 ;
-(void)_configureCell:(id)arg1 buttonType:(unsigned long long)arg2 ;
-(void)_presentPasswordVerificationForFlow:(unsigned long long)arg1 ;
-(void)_removeNonCredentialAccount:(/*^block*/id)arg1 ;
-(void)_removeDeviceBasedLoginAccount:(/*^block*/id)arg1 ;
-(id)_synchronouslyRemoveAccount:(id)arg1 ;
-(void)_handleNonceStorageRemoveError:(id)arg1 ;
-(void)_popOrDismissNavigationController;
-(void)_removeNonceWithCredential:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(id)initWithUserAccount:(id)arg1 imageDownloader:(id)arg2 settingsCallback:(id)arg3 ;
-(double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2 ;
-(double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(unsigned long long)supportedInterfaceOrientations;
-(id)_backgroundColor;
-(long long)preferredInterfaceOrientationForPresentation;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
@end

