/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:41 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBDeviceRequestScannerDelegate <NSObject>
@optional
-(void)scanner:(id)arg1 didError:(id)arg2 eventName:(id)arg3;

@required
-(void)scanner:(id)arg1 didFindUserCode:(id)arg2 deviceRequestDictionary:(id)arg3 moreComing:(BOOL)arg4;
-(void)scanner:(id)arg1 didRemoveUserCode:(id)arg2 moreComing:(BOOL)arg3;

@end

