/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:38 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>

@class FBFeedToolbox;

@interface FBDisplayTimeInvalidationDescriptionComponent : CKCompositeComponent {

	FBFeedToolbox* _toolbox;

}

@property (nonatomic,retain) FBFeedToolbox * toolbox;              //@synthesize toolbox=_toolbox - In the implementation block
+(id)newWithMessage:(id)arg1 image:(id)arg2 leftButtonTitle:(id)arg3 leftButtonAction:(CKTypedComponentAction<>)arg4 rightButtonTitle:(id)arg5 rightButtonAction:(CKTypedComponentAction<>)arg6 toolbox:(id)arg7 ;
-(FBFeedToolbox *)toolbox;
-(void)setToolbox:(FBFeedToolbox *)arg1 ;
-(void)entityTapped:(id)arg1 context:(id)arg2 ;
@end

