/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:41 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Facebook/Facebook-Structs.h>
@class FBMemEditAction, NSAttributedString;

@interface FBEditActionLayout : NSObject {

	BOOL _showDivider;
	double _contentWidth;
	CGRect _dividerFrame;
	CGRect _timestampLabelFrame;
	CGRect _messageLabelFrame;
	BOOL _expandMessage;
	FBMemEditAction* _editAction;
	NSAttributedString* _messageText;
	NSAttributedString* _timestampText;
	double _height;

}

@property (assign,nonatomic) double height;                                     //@synthesize height=_height - In the implementation block
@property (nonatomic,readonly) FBMemEditAction * editAction;                    //@synthesize editAction=_editAction - In the implementation block
@property (nonatomic,readonly) NSAttributedString * messageText;                //@synthesize messageText=_messageText - In the implementation block
@property (nonatomic,readonly) NSAttributedString * timestampText;              //@synthesize timestampText=_timestampText - In the implementation block
@property (nonatomic,readonly) CGRect dividerFrame;                             //@synthesize dividerFrame=_dividerFrame - In the implementation block
@property (nonatomic,readonly) CGRect timestampLabelFrame;                      //@synthesize timestampLabelFrame=_timestampLabelFrame - In the implementation block
@property (nonatomic,readonly) CGRect messageLabelFrame;                        //@synthesize messageLabelFrame=_messageLabelFrame - In the implementation block
@property (assign,nonatomic) BOOL expandMessage;                                //@synthesize expandMessage=_expandMessage - In the implementation block
+(CGColorRef)_timestampTextColor;
+(id)_timestampTextFont;
+(id)_messageTextFont;
+(id)timestampFont;
+(id)_messageFont;
+(CGColorRef)_messageTextColor;
+(id)_messageTextBoldFont;
+(CGColorRef)_truncationTextColor;
+(UIEdgeInsets)headerFooterMargin;
+(id)timestampColor;
+(id)truncationText;
+(FBEditActionLayoutParams)layoutParams;
+(UIEdgeInsets)padding;
+(id)dividerColor;
+(UIEdgeInsets)margin;
-(id)_attributedTimestampText;
-(id)_attributedMessageText;
-(NSAttributedString *)timestampText;
-(BOOL)expandMessage;
-(void)updateForWidth:(double)arg1 ;
-(CGRect)dividerFrame;
-(CGRect)timestampLabelFrame;
-(CGRect)messageLabelFrame;
-(id)initWithEditAction:(id)arg1 hasDivider:(BOOL)arg2 ;
-(void)setExpandMessage:(BOOL)arg1 ;
-(double)height;
-(FBMemEditAction *)editAction;
-(void)setHeight:(double)arg1 ;
-(NSAttributedString *)messageText;
@end

