/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:55 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface FBElementFamily : NSObject <NSCopying> {

	double _padding;
	NSString* _familyName;

}

@property (nonatomic,copy) NSString * familyName;              //@synthesize familyName=_familyName - In the implementation block
@property (assign,nonatomic) double padding;                   //@synthesize padding=_padding - In the implementation block
+(id)elementFamilyWithName:(id)arg1 padding:(double)arg2 ;
-(void)setFamilyName:(NSString *)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setPadding:(double)arg1 ;
-(double)padding;
-(NSString *)familyName;
@end

