/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:41 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBSectionComponentToolbox.h>
#import <Facebook/FBEmbeddedTabsHeightUpdateListener.h>

@protocol NSObject;
@class FIGTabsComponentToolbox, NSArray, FBEmbeddedTabsHeightUpdateListenerAnnouncer, FBEmbeddedTabBarListControllerListenerAnnouncer, NSString;

@interface FBEmbeddedTabsToolbox : FBSectionComponentToolbox <FBEmbeddedTabsHeightUpdateListener> {

	FIGTabsComponentToolbox* _figTabsComponentToolbox;
	id<NSObject> _headerComponentContext;
	NSArray* _tabsComponentContexts;
	FBEmbeddedTabsHeightUpdateListenerAnnouncer* _tabsHeightUpdateAnnouncer;
	FBEmbeddedTabBarListControllerListenerAnnouncer* _tabBarAnnouncer;

}

@property (nonatomic,readonly) FIGTabsComponentToolbox * figTabsComponentToolbox;                                    //@synthesize figTabsComponentToolbox=_figTabsComponentToolbox - In the implementation block
@property (nonatomic,readonly) id<NSObject> headerComponentContext;                                                  //@synthesize headerComponentContext=_headerComponentContext - In the implementation block
@property (nonatomic,copy,readonly) NSArray * tabsComponentContexts;                                                 //@synthesize tabsComponentContexts=_tabsComponentContexts - In the implementation block
@property (nonatomic,readonly) FBEmbeddedTabsHeightUpdateListenerAnnouncer * tabsHeightUpdateAnnouncer;              //@synthesize tabsHeightUpdateAnnouncer=_tabsHeightUpdateAnnouncer - In the implementation block
@property (nonatomic,readonly) FBEmbeddedTabBarListControllerListenerAnnouncer * tabBarAnnouncer;                    //@synthesize tabBarAnnouncer=_tabBarAnnouncer - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(FBEmbeddedTabBarListControllerListenerAnnouncer *)tabBarAnnouncer;
-(void)didUpdateTabContentHeightWhichNeedsBottomInset:(double)arg1 ;
-(id)initWithContext:(id)arg1 figTabsComponentToolbox:(id)arg2 headerComponentContext:(id)arg3 tabsComponentContexts:(id)arg4 tabsHeightUpdateAnnouncer:(id)arg5 tabBarAnnouncer:(id)arg6 ;
-(id<NSObject>)headerComponentContext;
-(FIGTabsComponentToolbox *)figTabsComponentToolbox;
-(NSArray *)tabsComponentContexts;
-(FBEmbeddedTabsHeightUpdateListenerAnnouncer *)tabsHeightUpdateAnnouncer;
@end

