/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:38 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBEntityCardContextItemsLoggerProtocol.h>

@protocol FBEntityCardsAnalyticsLogger;
@class FBEntityCardsAnalytics, NSString;

@interface FBEntityCardContextItemLogger : NSObject <FBEntityCardContextItemsLoggerProtocol> {

	id<FBEntityCardsAnalyticsLogger> _logger;
	FBEntityCardsAnalytics* _analytics;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)logImpressionForContextItem:(id)arg1 entityID:(id)arg2 contextItemSurface:(id)arg3 position:(unsigned long long)arg4 ;
-(void)logTapOnContextItem:(id)arg1 entityID:(id)arg2 contextItemSurface:(id)arg3 position:(unsigned long long)arg4 ;
-(id)initWithSession:(id)arg1 analytics:(id)arg2 contextItemSurface:(unsigned long long)arg3 moduleName:(id)arg4 ;
@end

