/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:33 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <Facebook/FBEventsDiscoverListFiltersViewDelegate.h>

@protocol FBEventsDiscoverListFiltersViewControllerDelegate;
@class FBUserSession, FBEventsDiscoverListFiltersView, NSString, UIImage, NSArray, NSMutableSet, FBEventsDiscoverSuggestionContext, FBEventAnalyticTracker;

@interface FBEventsDiscoverListFiltersViewController : UITableViewController <UIGestureRecognizerDelegate, FBEventsDiscoverListFiltersViewDelegate> {

	FBUserSession* _session;
	FBEventsDiscoverListFiltersView* _filtersView;
	NSString* _title;
	UIImage* _sectionIcon;
	NSString* _sectionTitle;
	NSArray* _categories;
	NSMutableSet* _selectedIndices;
	FBEventsDiscoverSuggestionContext* _suggestionContext;
	FBEventAnalyticTracker* _tracker;
	id<FBEventsDiscoverListFiltersViewControllerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<FBEventsDiscoverListFiltersViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_didTapOnBackground:(id)arg1 ;
-(void)filtersViewDidApplyFilters:(id)arg1 ;
-(void)filtersViewDidClearFilters:(id)arg1 ;
-(id)_extrasWithSuggestionContext;
-(id)initWithSession:(id)arg1 title:(id)arg2 sectionIcon:(id)arg3 sectionTitle:(id)arg4 categories:(id)arg5 selectedIndices:(id)arg6 suggestionContext:(id)arg7 tracker:(id)arg8 ;
-(void)setDelegate:(id<FBEventsDiscoverListFiltersViewControllerDelegate>)arg1 ;
-(double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2 ;
-(double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(id<FBEventsDiscoverListFiltersViewControllerDelegate>)delegate;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2 ;
-(unsigned long long)supportedInterfaceOrientations;
-(void)loadView;
-(long long)preferredInterfaceOrientationForPresentation;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
@end

