/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:33 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBEventDiscoveryToolbox.h>

@protocol FBNavigationCoordinator, FBIntentHandler, FBScrollingContentViewControllerListener;
@class FBUserSession, FBEventAnalyticTracker, FBEventActionResponder, FBScenePath, FBScenePathContext, FBLocationManager, NSString, FBEventCalendarStore, FBFeedToolbox;

@interface FBEventsDashboardToolbox : NSObject <FBEventDiscoveryToolbox> {

	FBEventActionResponder* _actionResponder;
	FBScenePath* _scenePath;
	FBScenePathContext* _scenePathContext;
	FBUserSession* _session;
	FBLocationManager* _locationManager;
	id<FBNavigationCoordinator> _navigationCoordinator;
	id<FBIntentHandler> _intentHandler;
	FBEventAnalyticTracker* _tracker;
	id<FBScrollingContentViewControllerListener> _sideFeedListener;
	NSString* _analyticsModule;
	FBEventCalendarStore* _calendarStore;
	FBFeedToolbox* _feedToolbox;

}

@property (nonatomic,readonly) FBEventActionResponder * actionResponder;                                   //@synthesize actionResponder=_actionResponder - In the implementation block
@property (nonatomic,copy,readonly) FBScenePath * scenePath;                                               //@synthesize scenePath=_scenePath - In the implementation block
@property (nonatomic,readonly) FBScenePathContext * scenePathContext;                                      //@synthesize scenePathContext=_scenePathContext - In the implementation block
@property (nonatomic,readonly) FBUserSession * session;                                                    //@synthesize session=_session - In the implementation block
@property (nonatomic,readonly) FBLocationManager * locationManager;                                        //@synthesize locationManager=_locationManager - In the implementation block
@property (nonatomic,readonly) id<FBNavigationCoordinator> navigationCoordinator;                          //@synthesize navigationCoordinator=_navigationCoordinator - In the implementation block
@property (nonatomic,readonly) id<FBIntentHandler> intentHandler;                                          //@synthesize intentHandler=_intentHandler - In the implementation block
@property (nonatomic,readonly) FBEventAnalyticTracker * tracker;                                           //@synthesize tracker=_tracker - In the implementation block
@property (nonatomic,readonly) id<FBScrollingContentViewControllerListener> sideFeedListener;              //@synthesize sideFeedListener=_sideFeedListener - In the implementation block
@property (nonatomic,copy,readonly) NSString * analyticsModule;                                            //@synthesize analyticsModule=_analyticsModule - In the implementation block
@property (nonatomic,readonly) FBEventCalendarStore * calendarStore;                                       //@synthesize calendarStore=_calendarStore - In the implementation block
@property (nonatomic,readonly) FBFeedToolbox * feedToolbox;                                                //@synthesize feedToolbox=_feedToolbox - In the implementation block
+(id)toolboxWithSession:(id)arg1 locationManager:(id)arg2 actionResponder:(id)arg3 analyticsModule:(id)arg4 scenePath:(id)arg5 scenePathContext:(id)arg6 navigationCoordinator:(id)arg7 intentHandler:(id)arg8 tracker:(id)arg9 feedToolbox:(id)arg10 ;
-(id<FBNavigationCoordinator>)navigationCoordinator;
-(id<FBIntentHandler>)intentHandler;
-(FBScenePath *)scenePath;
-(NSString *)analyticsModule;
-(FBFeedToolbox *)feedToolbox;
-(FBEventAnalyticTracker *)tracker;
-(id<FBScrollingContentViewControllerListener>)sideFeedListener;
-(id)initWithSession:(id)arg1 locationManager:(id)arg2 actionResponder:(id)arg3 analyticsModule:(id)arg4 scenePath:(id)arg5 scenePathContext:(id)arg6 navigationCoordinator:(id)arg7 intentHandler:(id)arg8 tracker:(id)arg9 feedToolbox:(id)arg10 ;
-(FBScenePathContext *)scenePathContext;
-(FBEventCalendarStore *)calendarStore;
-(FBUserSession *)session;
-(FBEventActionResponder *)actionResponder;
-(FBLocationManager *)locationManager;
@end

