/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:40 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/FBEventTicketRegistrationDataUpdateListener.h>
#import <libobjc.A.dylib/NSCopying.h>

@protocol FBEventTicketingIndividualTicketRegistrationDataDelegate;
@class NSMutableDictionary, NSMutableArray, NSString;

@interface FBEventTicketingIndividualTicketRegistrationData : NSObject <FBEventTicketRegistrationDataUpdateListener, NSCopying> {

	NSMutableDictionary* _mutableFormFields;
	NSMutableArray* _fieldsWithError;
	id<FBEventTicketingIndividualTicketRegistrationDataDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<FBEventTicketingIndividualTicketRegistrationDataDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)doesHaveError;
-(id)asJSONString;
-(void)updateValueForFormFieldFragment:(id)arg1 fieldName:(id)arg2 value:(id)arg3 hasError:(BOOL)arg4 ;
-(void)updateErrorForFormFieldFragment:(id)arg1 hasError:(BOOL)arg2 ;
-(id)stringValueForField:(id)arg1 ;
-(id)numberValueForField:(id)arg1 ;
-(id)valuesForField:(id)arg1 ;
-(id)vectorValueForField:(id)arg1 ;
-(id)valueForFormFieldFragment:(id)arg1 ;
-(id)dateValueForField:(id)arg1 ;
-(void)setDelegate:(id<FBEventTicketingIndividualTicketRegistrationDataDelegate>)arg1 ;
-(id)init;
-(id<FBEventTicketingIndividualTicketRegistrationDataDelegate>)delegate;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

