/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:38 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBFacecastWithGuestViewControllerDelegate <NSObject>
@required
-(void)facecastWithGuestViewControllerDidReceiveInvitation:(id)arg1;
-(void)facecastWithGuestViewControllerDidDismissInvitation:(id)arg1;
-(void)facecastWithGuestViewControllerDidAcceptInvitation:(id)arg1;
-(void)facecastWithGuestViewControllerDidEndGuestBroadcast:(id)arg1;
-(void)facecastWithGuestViewControllerDidReturnToBroadcast:(id)arg1;
-(void)facecastWithGuestViewControllerDidTapShare:(id)arg1;
-(void)facecastWithGuestViewControllerWillShowPermissionPrompt:(id)arg1;
-(void)facecastWithGuestViewControllerDidDismissPermissionPrompt:(id)arg1;

@end

