/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:35 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/CKCompositeComponent.h>
#import <Facebook/FBFeedUnitProviding.h>

@protocol FBQueriedFeedUnitFieldsProtocol, FBComponentControllerWorkingRangeListening;
@class FBMemModelObject, FBFeedStoryPositionTracker, NSString;

@interface FBFeedUnitImpressionTrackingComponent : CKCompositeComponent <FBFeedUnitProviding> {

	FBMemModelObject*<FBQueriedFeedUnitFieldsProtocol> _unit;
	FBFeedStoryPositionTracker* _positionTracker;
	id<FBComponentControllerWorkingRangeListening> _workingRangeListener;

}

@property (nonatomic,readonly) id<FBComponentControllerWorkingRangeListening> workingRangeListener;              //@synthesize workingRangeListener=_workingRangeListener - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)newWithUnit:(id)arg1 component:(id)arg2 toolbox:(id)arg3 ;
-(id)feedUnit;
-(id<FBComponentControllerWorkingRangeListening>)workingRangeListener;
-(long long)storyPosition;
@end

