/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:36 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBFeedComponentPhotoHandlerProtocol.h>

@class FBMemFeedStory, FBMemStoryAttachment, FBFeedComponentPhotoHandler, FBFeedToolbox, FBAnalyticsInfo, NSArray, NSString;

@interface FBFeedComponentPhotoCanvasHandler : NSObject <FBFeedComponentPhotoHandlerProtocol> {

	FBFeedComponentPhotoHandler* _photoHandler;
	FBFeedToolbox* _toolbox;
	FBAnalyticsInfo* _analyticsInfo;
	NSArray* _trackingCodes;
	NSArray* _trackingNodes;
	BOOL _sponsored;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) FBMemFeedStory * story; 
@property (nonatomic,readonly) FBMemStoryAttachment * attachment; 
+(id)handlerWithToolbox:(id)arg1 trackingCodes:(id)arg2 trackingNodes:(id)arg3 attachment:(id)arg4 story:(id)arg5 sponsored:(BOOL)arg6 eventBus:(id)arg7 analyticsInfo:(id)arg8 ;
+(BOOL)canHandleAttachment:(id)arg1 story:(id)arg2 ;
-(FBMemFeedStory *)story;
-(void)openPhoto:(id)arg1 fromViewOrLayer:(id)arg2 photoViewProvider:(id)arg3 photoViewOverlayProvider:(id)arg4 openInTaggingMode:(BOOL)arg5 showInspirationHeader:(BOOL)arg6 scrollBackToFeedDismissalEnabled:(BOOL)arg7 ;
-(void)openPhoto:(id)arg1 fromViewOrLayer:(id)arg2 ;
-(id)_viewForLayer:(id)arg1 ;
-(void)openStory;
-(FBMemStoryAttachment *)attachment;
@end

