/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:51 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <UIKit/UIView.h>

@class FBFeedUnitAsyncTransactionController, FBFeedAsyncTransactionLogger, NSString, UIView;

@interface FBFeedAsyncContainerComponentView : UIView {

	long long _identifier;
	FBFeedUnitAsyncTransactionController* _asyncTransactionController;
	FBFeedAsyncTransactionLogger* _asyncTransactionLogger;
	NSString* _nameSpace;
	UIView* _contentView;

}

@property (nonatomic,readonly) UIView * contentView;              //@synthesize contentView=_contentView - In the implementation block
-(void)fb_asyncTransactionContainerStateDidChange;
-(void)configureWithIdentifier:(long long)arg1 asyncTransactionController:(id)arg2 asyncTransactionLogger:(id)arg3 ;
-(void)_openTransaction;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)layoutSubviews;
-(UIView *)contentView;
@end

