/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>

@interface FBFeedUFICommentSectionComponent : CKCompositeComponent
+(id)newWithComments:(id)arg1 seeMoreCount:(unsigned long long)arg2 feedbackTarget:(id)arg3 editingComment:(id)arg4 cancelEditingAction:(CKTypedComponentAction<>)arg5 commitEditingAction:(CKTypedComponentAction<>)arg6 seeMoreCommentsAction:(CKTypedComponentAction<>)arg7 secondaryButtonAction:(CKTypedComponentAction<>)arg8 toolbox:(id)arg9 ;
@end

