/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:47 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>

@interface FBFeedGradientButtonComponent : CKCompositeComponent
+(id)newWithTitle:(id)arg1 images:(const unordered_map<unsigned long, UIImage *, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, UIImage *> > >*)arg2 selected:(BOOL)arg3 enabled:(BOOL)arg4 tapAction:(CKTypedComponentAction<>)arg5 fontFoundry:(id)arg6 ;
+(id)selectedBackgroundImage;
+(id)disabledBackgroundImage;
+(id)backgroundImage;
@end

