/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:47 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>

@interface FBFeedMenuUnitComponent : CKCompositeComponent {

	CKTypedComponentAction<> _undoAction;
	NSRange _undoRange;

}
+(id)newWithTitle:(id)arg1 undoAction:(CKTypedComponentAction<>)arg2 actionRows:(const vector<CKComponent *, std::__1::allocator<CKComponent *> >*)arg3 toolbox:(id)arg4 ;
+(id)undoButtonString;
+(id)accessibilityIdentifier;
-(void)didTapRichText:(id)arg1 context:(id)arg2 ;
@end

