/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:36 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>
#import <Facebook/FBFeedDisplayedPhotoProvider.h>

@class CKComponent, FBMemPhoto, FBFeedToolbox, NSString;

@interface FBFeedSinglePhotoAttachmentComponent : CKCompositeComponent <FBFeedDisplayedPhotoProvider> {

	CKComponent* _childComponent;
	double _maxHeightRatio;
	FBMemPhoto* _photo;
	FBFeedToolbox* _toolbox;

}

@property (nonatomic,retain) FBMemPhoto * photo;                    //@synthesize photo=_photo - In the implementation block
@property (nonatomic,retain) FBFeedToolbox * toolbox;               //@synthesize toolbox=_toolbox - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)newWithPhoto:(const FBFeedSinglePhotoAttachmentComponentPhotoGraphQL*)arg1 options:(const FBFeedSinglePhotoAttachmentComponentOptions*)arg2 storyInsets:(UIEdgeInsets)arg3 sponsored:(BOOL)arg4 photoHandler:(id)arg5 mediaForceTouchIntentTarget:(id)arg6 toolbox:(id)arg7 ;
+(void)setCapPortraitPhotoHeight:(BOOL)arg1 ;
-(FBFeedToolbox *)toolbox;
-(void)setToolbox:(FBFeedToolbox *)arg1 ;
-(CKComponentLayout*)computeLayoutThatFits:(CKSizeRange)arg1 restrictedToSize:(const CKComponentSize*)arg2 relativeToParentSize:(CGSize)arg3 ;
-(id)displayedPhoto;
-(void)setPhoto:(FBMemPhoto *)arg1 ;
-(FBMemPhoto *)photo;
@end

