/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:40 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBSectionedDataSourceReading;
#import <Facebook/Facebook-Structs.h>
@interface FBFeedScrollOffsetModifier : NSObject {

	id<FBSectionedDataSourceReading> _modelProvider;

}
-(void)scrollViewWillEndDragging:(id)arg1 withVelocity:(CGPoint)arg2 targetContentOffsetPtr:(inout CGPoint*)arg3 ;
-(id)initWithModelProvider:(id)arg1 ;
-(BOOL)_nudgeOffset:(CGPoint)arg1 inCollectionView:(id)arg2 targetContentOffset:(inout CGPoint*)arg3 ;
@end

