/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:50 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>
#import <Facebook/FBFormElementDelegate.h>

@class UINavigationController, FBFormElementViewRecycler, FBForm, NSString;

@interface FBFormViewController : UITableViewController <FBFormElementDelegate> {

	FBFormElementViewRecycler* _recycler;
	FBForm* _form;

}

@property (nonatomic,readonly) FBForm * form;                                       //@synthesize form=_form - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) UINavigationController * navController; 
-(id)indexPathForFormElement:(id)arg1 ;
-(void)didUpdateFormElement:(id)arg1 ;
-(id)formSectionWithSection:(long long)arg1 ;
-(id)_elementAtIndexPath:(id)arg1 ;
-(id)init;
-(void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3 ;
-(double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2 ;
-(void)viewDidLoad;
-(UINavigationController *)navController;
-(FBForm *)form;
@end

