/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:47 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class FBUserSession, NSObject, NSMutableDictionary, NSMutableSet;

@interface FBFriendingActionMemStore : NSObject {

	FBUserSession* _session;
	NSObject*<OS_dispatch_queue> _serialWorkQueue;
	NSMutableDictionary* _committedFriendingActions;
	NSMutableDictionary* _initialFriendshipStatuses;
	NSMutableDictionary* _pendingFriendingActions;
	int _transactionID;
	NSMutableSet* _syncingMemPersons;
	double _coldStartTime;
	double _foregroundingTime;

}
-(void)_didEnterBackground;
-(void)_didEnterForeground;
-(void)_updateAndCacheLastFriendingAction:(unsigned long long)arg1 andFriendshipStatus:(id)arg2 forPerson:(id)arg3 ;
-(unsigned long long)_generateNextTransactionID;
-(unsigned long long)_lastNonFailPendingFriendingActionForPerson:(id)arg1 ;
-(void)_syncFriendshipStatusWithServerForPerson:(id)arg1 ;
-(void)_friendshipStatusSyncSucceededForPerson:(id)arg1 ;
-(void)_friendshipStatusSyncFailedForPerson:(id)arg1 ;
-(void)_resetFriendingActionForPerson:(id)arg1 clearActionFail:(BOOL)arg2 ;
-(id)serialWorkQueue;
-(id)committedFriendingActions;
-(id)pendingFriendingActions;
-(id)proposeFriendingAction:(unsigned long long)arg1 targetPerson:(id)arg2 rollbackPerson:(id)arg3 ;
-(void)commitFriendingActionHandle:(id)arg1 ;
-(void)abortFriendingActionHandle:(id)arg1 ;
-(void)cancelFriendingActionHandle:(id)arg1 ;
-(void)dealloc;
-(id)initWithSession:(id)arg1 ;
@end

