/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:32 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBComponentTableViewDataSourceSectionHeaderHandler.h>

@class FBUserSession, FBComponentTableViewDataSource, FBFriendingStatefulWriteInterface, UITableView, NSString;

@interface FBFriendConfirmedNotificationTableViewSectionHelper : NSObject <FBComponentTableViewDataSourceSectionHeaderHandler> {

	FBUserSession* _session;
	FBComponentTableViewDataSource* _dataSource;
	FBFriendingStatefulWriteInterface* _statefulWriteInterface;
	long long _tableSectionHeaderStyle;
	UITableView* _tableView;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)statefulWriteInterface;
-(void)tableViewBecomesReady;
-(id)dataSource:(id)arg1 viewForHeaderInSection:(long long)arg2 ;
-(double)dataSource:(id)arg1 heightForHeaderInSection:(long long)arg2 ;
-(id)initWithSession:(id)arg1 tableView:(id)arg2 dataSource:(id)arg3 ;
-(void)insertAcceptedFriendRequestsCells:(id)arg1 ;
-(void)clearPYMKSection;
-(void)insertPYMKSuggestions:(id)arg1 andNumberOfNew:(unsigned long long)arg2 hasMoreObjects:(BOOL)arg3 ;
-(void)updatePYKMCell:(id)arg1 atIndex:(long long)arg2 ;
-(void)removePYKMCell:(id)arg1 atIndex:(long long)arg2 ;
-(id)reuseIdentifierForHeaderInSection:(long long)arg1 ;
-(id)titleForHeaderInSection:(long long)arg1 ;
@end

