/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:52 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/FBSmartClippingTextNode.h>

@interface FBFullBleedTextNode : FBSmartClippingTextNode {

	UIEdgeInsets _textInsets;

}

@property (nonatomic,readonly) CGSize calculatedTextSize; 
@property (nonatomic,readonly) CGRect textFrame; 
+(CGSize)textSizeWithAttributedString:(id)arg1 constrainedSize:(CGSize)arg2 ;
-(void)_staticInitialize;
-(CGSize)calculateSizeThatFits:(CGSize)arg1 ;
-(CGSize)calculatedTextSize;
-(double)_heightInflation;
-(id)init;
-(void)setFrame:(CGRect)arg1 ;
-(void)setPosition:(CGPoint)arg1 ;
-(void)setAttributedString:(id)arg1 ;
-(CGRect)textFrame;
@end

