/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:36 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/CKCompositeComponent.h>

@class FBMemFeedStory, FBMemGroupCommerceProductItem, NSArray, FBFeedSecondaryActionContext, FBComposerEditPostController;

@interface FBGroupSellActionButtonComponent : CKCompositeComponent {

	FBMemFeedStory* _story;
	FBMemGroupCommerceProductItem* _productItem;
	NSArray* _trackingCodes;
	NSArray* _trackingNodes;
	FBFeedSecondaryActionContext* _context;
	unsigned long long _layoutIdiom;
	FBComposerEditPostController* _editPostController;

}
+(id)newWithUnit:(id)arg1 toolbox:(id)arg2 ;
+(id)newWithUnit:(id)arg1 toolbox:(id)arg2 hidingEdit:(BOOL)arg3 ;
-(void)editTapped:(id)arg1 ;
-(void)toggleAvailabilityTapped:(id)arg1 ;
@end

