/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:32 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/FBMapSnapshotSpecifier.h>

@class NSArray, CLLocation, FBUserSession, UIImage, NSString;

@interface FBGraphSearchResultsPlacesMapSnapshotSpecifier : NSObject <FBMapSnapshotSpecifier> {

	NSArray* _coordinateList;
	CLLocation* _userLocation;
	FBUserSession* _session;
	UIImage* _annotationImage;
	UIImage* _userLocationAnnotationImage;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithCoordinateList:(id)arg1 userLocation:(id)arg2 session:(id)arg3 ;
-(id)requestForSize:(CGSize)arg1 ;
-(unsigned long long)decorator;
-(id)pinImage;
-(id)shimmeringImage;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
@end

