/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:40 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBGroupsBasicMemberActionSheetViewController.h>
#import <Facebook/FBGroupsMemberActionSheetViewControllerProtocol.h>

@class FBMemGroup, FBGroupDownloadRequestProvider, FBConsistentLookasideCacheObservationHandle;

@interface FBGroupsMemberActionSheetViewController : FBGroupsBasicMemberActionSheetViewController <FBGroupsMemberActionSheetViewControllerProtocol> {

	FBMemGroup* _group;
	FBGroupDownloadRequestProvider* _downloadProvider;
	FBConsistentLookasideCacheObservationHandle* _groupObservationHandle;

}
-(void)_loadGroup:(id)arg1 ;
-(void)_groupModelUpdated:(id)arg1 ;
-(id)initWithSession:(id)arg1 groupID:(id)arg2 ;
-(void)leaveGroupWithGroupID:(id)arg1 ;
-(id)groupWithGroupID:(id)arg1 ;
-(void)dealloc;
@end

