/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:47 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIImageView.h>

@class UIImageView, NSString;

@interface FBGroupsLandingPogCategoryView : UIImageView {

	UIImageView* _iconView;
	NSString* _category;

}

@property (nonatomic,copy) NSString * category;              //@synthesize category=_category - In the implementation block
+(id)whiteCircleBackgroundImage;
+(id)communityInterestIconImage;
-(id)init;
-(void)layoutSubviews;
-(void)removeFromSuperview;
-(void)setCategory:(NSString *)arg1 ;
-(NSString *)category;
@end

