/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:32 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/CKCompositeComponent.h>

@protocol FBGroupActionBarTapResponder;
@class FBGroupFeedActionBarModel, FBGroupToolbox;

@interface FBGroupFeedActionBarComponent : CKCompositeComponent {

	FBGroupFeedActionBarModel* _model;
	FBGroupToolbox* _toolbox;
	id<FBGroupActionBarTapResponder> _tapHandler;

}
+(id)newWithModel:(id)arg1 toolbox:(id)arg2 ;
-(void)createEventTapped:(id)arg1 ;
-(void)shareTapped:(id)arg1 ;
-(void)followTapped:(id)arg1 ;
-(void)showSecondaryActions:(id)arg1 ;
-(void)createGroupTapped:(id)arg1 ;
-(void)_segmentedComponent:(id)arg1 didSelectItemAtIndex:(id)arg2 ;
-(void)infoTapped:(id)arg1 ;
-(void)viewGroupInfoTapped:(id)arg1 ;
-(void)createGroupChatTapped:(id)arg1 ;
-(void)viewMembersTapped:(id)arg1 ;
-(void)viewPhotosTapped:(id)arg1 ;
-(void)addMemberTapped:(id)arg1 ;
-(void)cancelRequestTapped:(id)arg1 ;
-(void)editGroupNotificationSettingsTapped:(id)arg1 ;
-(void)favoriteTapped:(id)arg1 ;
-(void)joinTapped:(id)arg1 ;
-(void)leaveTapped:(id)arg1 ;
-(void)reportGroupTapped:(id)arg1 ;
-(void)chatTabBarItemTapped:(id)arg1 ;
-(void)searchGroupTapped:(id)arg1 ;
@end

