/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:55 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBImageProcessingConcurrentRequest.h>

@class NSURL, UIImage, NSError;

@interface FBImageProcessingAssetLoadRequest : FBImageProcessingConcurrentRequest {

	NSURL* _assetURL;
	BOOL _fullResolution;
	long long _targetDimension;
	UIImage* _image;
	NSError* _error;

}

@property (nonatomic,readonly) UIImage * image;              //@synthesize image=_image - In the implementation block
@property (nonatomic,readonly) NSError * error;              //@synthesize error=_error - In the implementation block
-(id)initWithAssetURL:(id)arg1 fullResolution:(BOOL)arg2 targetDimension:(long long)arg3 completion:(/*^block*/id)arg4 cancel:(/*^block*/id)arg5 ;
-(UIImage *)image;
-(void)clear;
-(NSError *)error;
-(void)executeWithContext:(id)arg1 ;
@end

