/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:46 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>
#import <Facebook/FBInstantGameChallengeHeaderViewDelegate.h>

@protocol FBInstantGameChallengeViewDelegate;
@class FBInstantGameUIMetrics, FBInstantGameChallengeHeaderView, UIView, FBCustomActivityIndicatorView;

@interface FBInstantGameChallengeView : UIView <FBInstantGameChallengeHeaderViewDelegate> {

	FBInstantGameUIMetrics* _metrics;
	FBInstantGameChallengeHeaderView* _headerView;
	UIView* _contentView;
	FBCustomActivityIndicatorView* _loadingIndicator;
	BOOL _showLoadingIndicator;
	id<FBInstantGameChallengeViewDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<FBInstantGameChallengeViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) BOOL showLoadingIndicator;                                           //@synthesize showLoadingIndicator=_showLoadingIndicator - In the implementation block
-(void)setShowLoadingIndicator:(BOOL)arg1 ;
-(void)tableHeaderViewDidTapCloseButton:(id)arg1 ;
-(void)setDelegate:(id<FBInstantGameChallengeViewDelegate>)arg1 ;
-(void)layoutSubviews;
-(id<FBInstantGameChallengeViewDelegate>)delegate;
-(id)initWithContentView:(id)arg1 ;
-(BOOL)showLoadingIndicator;
@end

