/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:34 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBInlineComposerListConfiguring.h>

@protocol FBQueriedActorFieldsProtocol;
@class NSString, NSURL, FBMemModelObject;

@interface FBInlineComposerListConfigurationSetup : NSObject <FBInlineComposerListConfiguring> {

	BOOL _disableTapProfilePictureAction;
	NSString* _filterText;
	NSURL* _profilePictureURL;
	NSURL* _profileBadgeURL;
	FBMemModelObject*<FBQueriedActorFieldsProtocol> _actor;
	long long _mainAction;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) BOOL disableTapProfilePictureAction;                                //@synthesize disableTapProfilePictureAction=_disableTapProfilePictureAction - In the implementation block
@property (nonatomic,copy) NSString * filterText;                                                //@synthesize filterText=_filterText - In the implementation block
@property (nonatomic,copy) NSURL * profilePictureURL;                                            //@synthesize profilePictureURL=_profilePictureURL - In the implementation block
@property (nonatomic,copy) NSURL * profileBadgeURL;                                              //@synthesize profileBadgeURL=_profileBadgeURL - In the implementation block
@property (assign,nonatomic) FBMemModelObject*<FBQueriedActorFieldsProtocol> actor;              //@synthesize actor=_actor - In the implementation block
@property (assign,nonatomic) long long mainAction;                                               //@synthesize mainAction=_mainAction - In the implementation block
-(NSURL *)profilePictureURL;
-(BOOL)disableTapProfilePictureAction;
-(void)setDisableTapProfilePictureAction:(BOOL)arg1 ;
-(NSString *)filterText;
-(void)setFilterText:(NSString *)arg1 ;
-(void)setProfilePictureURL:(NSURL *)arg1 ;
-(NSURL *)profileBadgeURL;
-(void)setProfileBadgeURL:(NSURL *)arg1 ;
-(id)init;
-(void)setMainAction:(long long)arg1 ;
-(long long)mainAction;
-(FBMemModelObject*<FBQueriedActorFieldsProtocol>)actor;
-(void)setActor:(FBMemModelObject*<FBQueriedActorFieldsProtocol>)arg1 ;
@end

