/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:40 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBGametimeScoreUpdaterListener.h>

@protocol FBInlineComposerProductionPromptDownloaderDelegate;
@class FBUserSession, FBMemProductionPrompt, NSMutableSet, NSArray, NSMutableArray, NSString;

@interface FBInlineComposerProductionPromptLoader : NSObject <FBGametimeScoreUpdaterListener> {

	FBUserSession* _session;
	FBMemProductionPrompt* _currentProductionPrompt;
	NSMutableSet* _stickerDownloaders;
	NSArray* _currentProductionPrompts;
	NSMutableArray* _currentInlineComposerPrompts;
	NSMutableSet* _processedProductionPromptIDs;
	id<FBInlineComposerProductionPromptDownloaderDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<FBInlineComposerProductionPromptDownloaderDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)matchData:(id)arg1 didUpdateForMatchID:(id)arg2 ;
-(void)_fetchExtraInfo:(id)arg1 ;
-(void)_loadGametimeMetadataForMatchID:(id)arg1 ;
-(void)_loadCameraFramesForProductionPrompt:(id)arg1 ;
-(void)_loadSuggestedSouvenirForProductionPrompt:(id)arg1 ;
-(void)_didFetchExtraInfo:(id)arg1 forProductionPrompt:(id)arg2 ;
-(void)_didFetchPromptContent:(id)arg1 forProductionPrompt:(id)arg2 ;
-(void)loadInlineComposerPromptForProductionPrompts:(id)arg1 ;
-(void)setDelegate:(id<FBInlineComposerProductionPromptDownloaderDelegate>)arg1 ;
-(id<FBInlineComposerProductionPromptDownloaderDelegate>)delegate;
-(id)initWithSession:(id)arg1 ;
@end

