/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:50 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSArray, NSString;

@interface FBInstantGameListGameSocialInfo : FBValueObject <NSCopying> {

	NSArray* _profileImageURLs;
	NSString* _socialText;

}

@property (nonatomic,copy,readonly) NSArray * profileImageURLs;              //@synthesize profileImageURLs=_profileImageURLs - In the implementation block
@property (nonatomic,copy,readonly) NSString * socialText;                   //@synthesize socialText=_socialText - In the implementation block
-(NSArray *)profileImageURLs;
-(id)initWithProfileImageURLs:(id)arg1 socialText:(id)arg2 ;
-(NSString *)socialText;
@end

