/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:36 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSArray;

@interface FBInlineComposerPublisherBarConfig : FBValueObject <NSCopying> {

	NSArray* _buttonTypes;
	unsigned long long _style;

}

@property (nonatomic,copy,readonly) NSArray * buttonTypes;              //@synthesize buttonTypes=_buttonTypes - In the implementation block
@property (nonatomic,readonly) unsigned long long style;                //@synthesize style=_style - In the implementation block
-(id)initWithButtonTypes:(id)arg1 style:(unsigned long long)arg2 ;
-(NSArray *)buttonTypes;
-(unsigned long long)style;
@end

