/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:44 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/ASDisplayNode.h>
#import <libobjc.A.dylib/MKMapViewDelegate.h>

@protocol FBInteractiveMapNodeDelegate;
@class MKMapView, NSArray, NSString;

@interface FBInteractiveMapNode : ASDisplayNode <MKMapViewDelegate> {

	MKMapView* _mapView;
	BOOL _showsUserLocation;
	id<FBInteractiveMapNodeDelegate> _delegate;
	double _pointAnnotationScale;
	unsigned long long _mapType;
	NSArray* _pointAnnotations;
	SCD_Struct_FB48 _region;

}

@property (assign,nonatomic) unsigned long long mapType;                                    //@synthesize mapType=_mapType - In the implementation block
@property (assign,nonatomic) SCD_Struct_FB47 region;                                        //@synthesize region=_region - In the implementation block
@property (nonatomic,copy) NSArray * pointAnnotations;                                      //@synthesize pointAnnotations=_pointAnnotations - In the implementation block
@property (assign,nonatomic,__weak) id<FBInteractiveMapNodeDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) BOOL showsUserLocation;                                        //@synthesize showsUserLocation=_showsUserLocation - In the implementation block
@property (assign,nonatomic) double pointAnnotationScale;                                   //@synthesize pointAnnotationScale=_pointAnnotationScale - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_staticInitialize;
-(void)setPointAnnotations:(NSArray *)arg1 ;
-(void)_lazilyLoadMapViewIfNecessary;
-(NSArray *)pointAnnotations;
-(id)initWithMapType:(unsigned long long)arg1 region:(SCD_Struct_FB47)arg2 pointAnnotations:(id)arg3 ;
-(void)setPointAnnotationScale:(double)arg1 ;
-(double)pointAnnotationScale;
-(void)setDelegate:(id<FBInteractiveMapNodeDelegate>)arg1 ;
-(id<FBInteractiveMapNodeDelegate>)delegate;
-(void)layout;
-(void)setRegion:(SCD_Struct_FB47)arg1 ;
-(SCD_Struct_FB47)region;
-(unsigned long long)mapType;
-(void)setMapType:(unsigned long long)arg1 ;
-(BOOL)showsUserLocation;
-(void)didLoad;
-(void)setShowsUserLocation:(BOOL)arg1 ;
-(void)mapViewDidFinishRenderingMap:(id)arg1 fullyRendered:(BOOL)arg2 ;
@end

