/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:58 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/FBGraphQLInput.h>

@class NSString, NSNumber;

@interface FBInstantGameAddScoreData : FBGraphQLInput {

	NSString* _clientMutationId;
	NSString* _actorId;
	NSString* _gameId;
	NSNumber* _score;
	NSString* _threadId;
	NSString* _storyId;
	NSString* _groupId;
	NSString* _sendAdmin;
	NSString* _sessionId;

}

@property (nonatomic,copy) NSString * clientMutationId;              //@synthesize clientMutationId=_clientMutationId - In the implementation block
@property (nonatomic,copy) NSString * actorId;                       //@synthesize actorId=_actorId - In the implementation block
@property (nonatomic,copy) NSString * gameId;                        //@synthesize gameId=_gameId - In the implementation block
@property (nonatomic,copy) NSNumber * score;                         //@synthesize score=_score - In the implementation block
@property (nonatomic,copy) NSString * threadId;                      //@synthesize threadId=_threadId - In the implementation block
@property (nonatomic,copy) NSString * storyId;                       //@synthesize storyId=_storyId - In the implementation block
@property (nonatomic,copy) NSString * groupId;                       //@synthesize groupId=_groupId - In the implementation block
@property (nonatomic,copy) NSString * sendAdmin;                     //@synthesize sendAdmin=_sendAdmin - In the implementation block
@property (nonatomic,copy) NSString * sessionId;                     //@synthesize sessionId=_sessionId - In the implementation block
-(void)setActorId:(NSString *)arg1 ;
-(void)setClientMutationId:(NSString *)arg1 ;
-(NSString *)clientMutationId;
-(void)setStoryId:(NSString *)arg1 ;
-(NSString *)storyId;
-(NSString *)actorId;
-(void)setGameId:(NSString *)arg1 ;
-(void)setSendAdmin:(NSString *)arg1 ;
-(NSString *)gameId;
-(const FBGraphQLInputField*)fieldsMetadataWithOutLength:(out int*)arg1 ;
-(NSString *)sendAdmin;
-(NSString *)sessionId;
-(void)setSessionId:(NSString *)arg1 ;
-(void)setScore:(NSNumber *)arg1 ;
-(NSNumber *)score;
-(void)setGroupId:(NSString *)arg1 ;
-(NSString *)groupId;
-(NSString *)threadId;
-(void)setThreadId:(NSString *)arg1 ;
@end

