/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:01:01 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/FBReachabilityListener.h>

@class FBReachabilityAnnouncer, NSString;

@interface FBIosReachabilityAnnouncerAdaptor : NSObject <FBReachabilityListener> {

	FBReachabilityAnnouncer* _reachabilityAnnouncer;
	function<void (unsigned long, unsigned long)>* _reachabilityStateCallback;

}

@property (readonly) unsigned long long reachabilityState; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)reachabilityStateChangedTo:(unsigned long long)arg1 from:(unsigned long long)arg2 ;
-(unsigned long long)reachabilityState;
-(id)initWithReachabilityAnnouncer:(id)arg1 reachabilityStateCallback:(function<void (unsigned long, unsigned long)>*)arg2 ;
-(id)initWithReachabilityStateCallback:(function<void (unsigned long, unsigned long)>*)arg1 ;
-(void)dealloc;
@end

