/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:36 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>
#import <Facebook/FIGCardContentLandscapeAttachmentRightCompliant.h>

@class NSString, FBFeedToolbox, NSArray;

@interface FBJoinGroupActionCompactButtonComponent : CKCompositeComponent <FIGCardContentLandscapeAttachmentRightCompliant> {

	FBJoinGroupActionCompactButtonComponentGraphQL* _group;
	CKTypedComponentAction<> _joinAction;
	CKTypedComponentAction<> _leaveAction;
	NSString* _source;
	FBFeedToolbox* _toolbox;
	NSArray* _trackingCodes;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)newWithGroup:(const FBJoinGroupActionCompactButtonComponentGraphQL*)arg1 joinAction:(CKTypedComponentAction<>)arg2 leaveAction:(CKTypedComponentAction<>)arg3 images:(const unordered_map<unsigned long, UIImage *, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, UIImage *> > >Ref)arg4 source:(id)arg5 trackingCodes:(id)arg6 toolbox:(id)arg7 ;
-(void)didTapJoinGroupButton;
@end

