/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:30 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>

@interface FBLiveVideoInfoComponent : CKCompositeComponent
+(id)newWithActorProfileImageURI:(id)arg1 isVerifiedProfile:(BOOL)arg2 title:(id)arg3 subtitle:(id)arg4 options:(const FBVideoInfoComponentOptions*)arg5 toolbox:(id)arg6 ;
@end

