/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:38 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/CKCompositeComponent.h>

@class FBFeedToolbox;

@interface FBLightningBoltOverlayComponent : CKCompositeComponent {

	BOOL _boltVisible;
	FBFeedToolbox* _toolbox;

}

@property (assign,nonatomic) BOOL boltVisible;                     //@synthesize boltVisible=_boltVisible - In the implementation block
@property (nonatomic,retain) FBFeedToolbox * toolbox;              //@synthesize toolbox=_toolbox - In the implementation block
+(id)newWithComponent:(id)arg1 boltVisible:(BOOL)arg2 toolbox:(id)arg3 ;
-(FBFeedToolbox *)toolbox;
-(void)setToolbox:(FBFeedToolbox *)arg1 ;
-(BOOL)boltVisible;
-(void)setBoltVisible:(BOOL)arg1 ;
@end

