/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:33 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBModalContainerViewControllerDelegate.h>
#import <Facebook/FBWebViewContainerControllerDelegate.h>

@protocol FBNavigationCoordinator;
@class FBUserSession, NSString;

@interface FBLocalNewsWebViewCoordinator : NSObject <FBModalContainerViewControllerDelegate, FBWebViewContainerControllerDelegate> {

	FBUserSession* _session;
	id<FBNavigationCoordinator> _navigationCoordinator;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dismissViewController:(id)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(id)initWithSession:(id)arg1 navigationCoordinator:(id)arg2 ;
-(void)dismissModalContainerViewController:(id)arg1 ;
-(void)dismissWebViewContainerController:(id)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)openURL:(id)arg1 feedback:(id)arg2 trackingCodes:(id)arg3 browserSurfaceData:(id)arg4 ;
@end

