/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:35 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/CKCompositeComponent.h>

@class FBMemContactRecommendationField, FBMemPage, FBUserSession, FBFeedToolbox, CKButtonComponent, FBPopoverActionSheet, FBLocalFeedbackActionHandler, NSString;

@interface FBLocalReviewDetailsStoryHeaderComponent : CKCompositeComponent {

	BOOL _isViewerReview;
	FBMemContactRecommendationField* _review;
	FBMemPage* _page;
	FBUserSession* _session;
	FBFeedToolbox* _toolbox;
	CKButtonComponent* _buttonComponent;
	FBPopoverActionSheet* _menuPopover;
	FBLocalFeedbackActionHandler* _actionHandler;
	NSString* _pageId;

}
+(id)newWithReview:(id)arg1 page:(id)arg2 profileImage:(id)arg3 privacyIconName:(id)arg4 context:(id)arg5 ;
-(void)showSecondaryActionMenu:(id)arg1 ;
-(void)didTapName;
-(id)buildDropDownMenuButtons;
-(void)didTapDelete;
-(id)buttonItemWithAction:(SEL)arg1 title:(id)arg2 glyphName:(unsigned long long)arg3 ;
-(void)didTapEdit;
-(void)didTapReport;
@end

