/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:35 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKStatefulViewComponent.h>

@class NSString;

@interface FBLocalPhotoMenuTextFieldComponent : CKStatefulViewComponent {

	NSString* _text;
	NSString* _placeholder;
	CKTypedComponentAction<> _textFieldEndsEditingAction;

}

@property (nonatomic,copy,readonly) NSString * text;                                             //@synthesize text=_text - In the implementation block
@property (nonatomic,copy,readonly) NSString * placeholder;                                      //@synthesize placeholder=_placeholder - In the implementation block
@property (nonatomic,readonly) CKTypedComponentAction<> textFieldEndsEditingAction;              //@synthesize textFieldEndsEditingAction=_textFieldEndsEditingAction - In the implementation block
+(id)newWithText:(id)arg1 placeholder:(id)arg2 textFieldEndsEditingAction:(CKTypedComponentAction<>)arg3 uniqueIdentifier:(id)arg4 ;
-(CKTypedComponentAction<>)textFieldEndsEditingAction;
-(NSString *)text;
-(NSString *)placeholder;
@end

