/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:33 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <MapKit/MKPointAnnotation.h>

@class FBMemVideo;

@interface FBLocalNewsLiveMapAnnotation : MKPointAnnotation {

	FBMemVideo* _liveVideo;

}

@property (nonatomic,retain) FBMemVideo * liveVideo;              //@synthesize liveVideo=_liveVideo - In the implementation block
+(id)newWithLiveVideo:(id)arg1 coordinate:(CLLocationCoordinate2D)arg2 ;
-(FBMemVideo *)liveVideo;
-(void)setLiveVideo:(FBMemVideo *)arg1 ;
@end

