/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:42 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class CLLocation, FBLocationFilterRadiusSelectorModel;

@interface FBLocationFilterCurrentLocationModel : FBValueObject <NSCopying> {

	BOOL _isSelected;
	long long _selectedRadiusMiles;
	CLLocation* _viewerLocation;
	FBLocationFilterRadiusSelectorModel* _radiusSelectorModel;

}

@property (nonatomic,readonly) BOOL isSelected;                                                             //@synthesize isSelected=_isSelected - In the implementation block
@property (nonatomic,readonly) long long selectedRadiusMiles;                                               //@synthesize selectedRadiusMiles=_selectedRadiusMiles - In the implementation block
@property (nonatomic,copy,readonly) CLLocation * viewerLocation;                                            //@synthesize viewerLocation=_viewerLocation - In the implementation block
@property (nonatomic,copy,readonly) FBLocationFilterRadiusSelectorModel * radiusSelectorModel;              //@synthesize radiusSelectorModel=_radiusSelectorModel - In the implementation block
-(long long)selectedRadiusMiles;
-(CLLocation *)viewerLocation;
-(FBLocationFilterRadiusSelectorModel *)radiusSelectorModel;
-(id)initWithIsSelected:(BOOL)arg1 selectedRadiusMiles:(long long)arg2 viewerLocation:(id)arg3 radiusSelectorModel:(id)arg4 ;
-(BOOL)isSelected;
@end

