/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:43 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <UIKit/UIView.h>
#import <Facebook/FBMailShareSheetEmailNotSupportedViewDelegate.h>

@protocol FBMailShareSheetInterstitialViewDelegate;
@class UIView;

@interface FBMailShareSheetInterstitialView : UIView <FBMailShareSheetEmailNotSupportedViewDelegate> {

	UIView* _stateView;
	id<FBMailShareSheetInterstitialViewDelegate> _delgate;
	unsigned long long _state;

}

@property (assign,nonatomic,__weak) id<FBMailShareSheetInterstitialViewDelegate> delgate;              //@synthesize delgate=_delgate - In the implementation block
@property (assign,nonatomic) unsigned long long state;                                                 //@synthesize state=_state - In the implementation block
-(id<FBMailShareSheetInterstitialViewDelegate>)delgate;
-(void)setDelgate:(id<FBMailShareSheetInterstitialViewDelegate>)arg1 ;
-(id)_viewForState:(unsigned long long)arg1 ;
-(void)mailShareSheetEmailNotSupportedViewCloseButtonWasPressed:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(unsigned long long)state;
-(void)setState:(unsigned long long)arg1 ;
@end

