/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:30 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBExperimentContext.h>

@interface FBMediaPickerVideoImprovementsExperimentContext : FBExperimentContext {

	BOOL _autoplayOnAppearance;
	BOOL _autoplayInSouvenirsPicker;
	BOOL _autoplayOnSelection;
	BOOL _fnfMemoryOptEnabled;
	BOOL _fnfEnabled;
	BOOL _playWhileScrolling;
	long long _autoplayCapacityHighEnd;
	long long _autoplayCapacityLowEnd;

}

@property (assign,nonatomic) BOOL autoplayOnAppearance;                      //@synthesize autoplayOnAppearance=_autoplayOnAppearance - In the implementation block
@property (assign,nonatomic) BOOL autoplayInSouvenirsPicker;                 //@synthesize autoplayInSouvenirsPicker=_autoplayInSouvenirsPicker - In the implementation block
@property (assign,nonatomic) BOOL autoplayOnSelection;                       //@synthesize autoplayOnSelection=_autoplayOnSelection - In the implementation block
@property (assign,nonatomic) BOOL fnfMemoryOptEnabled;                       //@synthesize fnfMemoryOptEnabled=_fnfMemoryOptEnabled - In the implementation block
@property (assign,nonatomic) BOOL fnfEnabled;                                //@synthesize fnfEnabled=_fnfEnabled - In the implementation block
@property (assign,nonatomic) BOOL playWhileScrolling;                        //@synthesize playWhileScrolling=_playWhileScrolling - In the implementation block
@property (assign,nonatomic) long long autoplayCapacityHighEnd;              //@synthesize autoplayCapacityHighEnd=_autoplayCapacityHighEnd - In the implementation block
@property (assign,nonatomic) long long autoplayCapacityLowEnd;               //@synthesize autoplayCapacityLowEnd=_autoplayCapacityLowEnd - In the implementation block
+(id)universeName;
+(id)parameterConfigurations;
+(unsigned)mobileconfigConfigSpecifier;
+(id)configurationName;
-(void)logExposure;
-(long long)autoplayCapacityHighEnd;
-(long long)autoplayCapacityLowEnd;
-(BOOL)autoplayInSouvenirsPicker;
-(BOOL)autoplayOnAppearance;
-(BOOL)autoplayOnSelection;
-(BOOL)fnfEnabled;
-(BOOL)fnfMemoryOptEnabled;
-(BOOL)playWhileScrolling;
-(void)setAutoplayOnAppearance:(BOOL)arg1 ;
-(void)setAutoplayInSouvenirsPicker:(BOOL)arg1 ;
-(void)setAutoplayOnSelection:(BOOL)arg1 ;
-(void)setFnfMemoryOptEnabled:(BOOL)arg1 ;
-(void)setFnfEnabled:(BOOL)arg1 ;
-(void)setPlayWhileScrolling:(BOOL)arg1 ;
-(void)setAutoplayCapacityHighEnd:(long long)arg1 ;
-(void)setAutoplayCapacityLowEnd:(long long)arg1 ;
@end

