/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:46 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/FBModalContainerViewController.h>
#import <Facebook/FBInAppNotificationEligibilityProtocol.h>

@protocol FBMinimizableContentDelegate;
@class FBUserSession, FBMinimizableModalsDismissAnimator, FBMinimizableModalsPresentAnimator, FBMinimizedTabBrowserZoomPresentAnimator, FBMinimizedTabBrowserZoomDismissAnimator, UIViewController, FBMinimizedTabBarBrowserColletionViewCell;

@interface FBMinimizableContentViewController : FBModalContainerViewController <FBInAppNotificationEligibilityProtocol> {

	FBUserSession* _session;
	FBMinimizableModalsDismissAnimator* _dismissAnimator;
	FBMinimizableModalsPresentAnimator* _presentAnimator;
	FBMinimizedTabBrowserZoomPresentAnimator* _zoomPresentAnimator;
	FBMinimizedTabBrowserZoomDismissAnimator* _zoomDismissAnimator;
	UIViewController*<FBMinimizableContentDelegate> _minimizableContentDelegate;
	FBMinimizedTabBarBrowserColletionViewCell* _correspondTab;
	CGRect _correspondTabFrame;

}

@property (assign,nonatomic) CGRect correspondTabFrame;                                                     //@synthesize correspondTabFrame=_correspondTabFrame - In the implementation block
@property (assign,nonatomic,__weak) FBMinimizedTabBarBrowserColletionViewCell * correspondTab;              //@synthesize correspondTab=_correspondTab - In the implementation block
-(BOOL)inAppNotificationBeeperManager:(id)arg1 shouldShowNotification:(id)arg2 ;
-(BOOL)inAppNotificationBeeperManager:(id)arg1 shouldShowFacecastNotification:(id)arg2 broadcaster:(id)arg3 ;
-(id)initWithContentViewController:(id)arg1 session:(id)arg2 ;
-(CGRect)correspondTabFrame;
-(void)setCorrespondTabFrame:(CGRect)arg1 ;
-(FBMinimizedTabBarBrowserColletionViewCell *)correspondTab;
-(void)setCorrespondTab:(FBMinimizedTabBarBrowserColletionViewCell *)arg1 ;
-(id)contentViewController;
-(id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3 ;
-(id)animationControllerForDismissedController:(id)arg1 ;
@end

