/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:43 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBMLPhotoUploaderListener;
@class FBMLPhotoUploader, SRQueueDispatcher;

@interface FBMLPhotoUploaderSubscription : NSObject {

	FBMLPhotoUploader* _photoUploader;
	id<FBMLPhotoUploaderListener> _listener;
	SRQueueDispatcher* _performer;

}

@property (nonatomic,retain) FBMLPhotoUploader * photoUploader;                          //@synthesize photoUploader=_photoUploader - In the implementation block
@property (assign,nonatomic,__weak) id<FBMLPhotoUploaderListener> listener;              //@synthesize listener=_listener - In the implementation block
@property (nonatomic,retain) SRQueueDispatcher * performer;                              //@synthesize performer=_performer - In the implementation block
-(FBMLPhotoUploader *)photoUploader;
-(void)setPhotoUploader:(FBMLPhotoUploader *)arg1 ;
-(void)setPerformer:(SRQueueDispatcher *)arg1 ;
-(SRQueueDispatcher *)performer;
-(id<FBMLPhotoUploaderListener>)listener;
-(void)setListener:(id<FBMLPhotoUploaderListener>)arg1 ;
@end

