/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:43 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBMLPhotosGridState, NSArray;

@interface FBMLPhotosGridDelta : NSObject {

	FBMLPhotosGridState* _oldState;
	NSArray* _updatedCellDatas;
	NSArray* _updatedPhotos;
	NSArray* _updatedPhotosPendingUpload;
	NSArray* _updatedPlaceholderImages;
	NSArray* _sameObjectMappingItems;
	NSArray* _updateItems;
	long long _updatedLimitPhotosToDisplay;

}

@property (nonatomic,retain) FBMLPhotosGridState * oldState;                     //@synthesize oldState=_oldState - In the implementation block
@property (nonatomic,copy) NSArray * updatedCellDatas;                           //@synthesize updatedCellDatas=_updatedCellDatas - In the implementation block
@property (nonatomic,copy) NSArray * updatedPhotos;                              //@synthesize updatedPhotos=_updatedPhotos - In the implementation block
@property (nonatomic,copy) NSArray * updatedPhotosPendingUpload;                 //@synthesize updatedPhotosPendingUpload=_updatedPhotosPendingUpload - In the implementation block
@property (nonatomic,copy) NSArray * updatedPlaceholderImages;                   //@synthesize updatedPlaceholderImages=_updatedPlaceholderImages - In the implementation block
@property (nonatomic,copy) NSArray * sameObjectMappingItems;                     //@synthesize sameObjectMappingItems=_sameObjectMappingItems - In the implementation block
@property (nonatomic,copy) NSArray * updateItems;                                //@synthesize updateItems=_updateItems - In the implementation block
@property (assign,nonatomic) long long updatedLimitPhotosToDisplay;              //@synthesize updatedLimitPhotosToDisplay=_updatedLimitPhotosToDisplay - In the implementation block
-(void)setUpdatedCellDatas:(NSArray *)arg1 ;
-(void)setUpdatedPhotos:(NSArray *)arg1 ;
-(void)setSameObjectMappingItems:(NSArray *)arg1 ;
-(void)setUpdateItems:(NSArray *)arg1 ;
-(void)setUpdatedLimitPhotosToDisplay:(long long)arg1 ;
-(void)setUpdatedPlaceholderImages:(NSArray *)arg1 ;
-(void)setUpdatedPhotosPendingUpload:(NSArray *)arg1 ;
-(NSArray *)updatedCellDatas;
-(NSArray *)sameObjectMappingItems;
-(NSArray *)updatedPhotos;
-(NSArray *)updatedPhotosPendingUpload;
-(NSArray *)updatedPlaceholderImages;
-(long long)updatedLimitPhotosToDisplay;
-(NSArray *)updateItems;
-(FBMLPhotosGridState *)oldState;
-(void)setOldState:(FBMLPhotosGridState *)arg1 ;
@end

