/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:01:01 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <libobjc.A.dylib/NSCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface FBMThreadMuteSettingsUpdate : NSObject <NSCoding, NSCopying> {

	unsigned long long _subtype;
	long long _messageNotifications_mutedUntil;
	unsigned long long _mentions_mentionMuteSetting;
	unsigned long long _reactions_reactionMuteSetting;

}
+(id)mentionsWithMentionMuteSetting:(unsigned long long)arg1 ;
+(id)messageNotificationsWithMutedUntil:(long long)arg1 ;
+(id)reactionsWithReactionMuteSetting:(unsigned long long)arg1 ;
-(void)matchMessageNotifications:(/*^block*/id)arg1 mentions:(/*^block*/id)arg2 reactions:(/*^block*/id)arg3 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

