/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:01:01 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class FBMSyncedThreadKey, NSString;

@interface FBMThreadParticipationInfoDeliveryReceiptUpdate : FBValueObject <NSCopying> {

	FBMSyncedThreadKey* _threadKey;
	NSString* _userId;
	unsigned long long _updatedTimestamp;

}

@property (nonatomic,copy,readonly) FBMSyncedThreadKey * threadKey;              //@synthesize threadKey=_threadKey - In the implementation block
@property (nonatomic,copy,readonly) NSString * userId;                           //@synthesize userId=_userId - In the implementation block
@property (nonatomic,readonly) unsigned long long updatedTimestamp;              //@synthesize updatedTimestamp=_updatedTimestamp - In the implementation block
-(id)initWithThreadKey:(id)arg1 userId:(id)arg2 updatedTimestamp:(unsigned long long)arg3 ;
-(unsigned long long)updatedTimestamp;
-(FBMSyncedThreadKey *)threadKey;
-(NSString *)userId;
@end

