/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:43 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBMUServiceURLSaveStatusChangeListenerDelegate;
@class FBMUServiceSession, NSURL;

@interface FBMUServiceURLSaveStatusChangeListener : NSObject {

	FBMUServiceSession* _session;
	NSURL* _url;
	unsigned long long _status;
	id<FBMUServiceURLSaveStatusChangeListenerDelegate> _delegate;

}

@property (nonatomic,readonly) FBMUServiceSession * session;                                                  //@synthesize session=_session - In the implementation block
@property (nonatomic,readonly) NSURL * url;                                                                   //@synthesize url=_url - In the implementation block
@property (nonatomic,readonly) unsigned long long status;                                                     //@synthesize status=_status - In the implementation block
@property (assign,nonatomic,__weak) id<FBMUServiceURLSaveStatusChangeListenerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)saveStatusChanged:(id)arg1 ;
-(id)initWithSession:(id)arg1 URL:(id)arg2 ;
-(void)setDelegate:(id<FBMUServiceURLSaveStatusChangeListenerDelegate>)arg1 ;
-(void)dealloc;
-(id<FBMUServiceURLSaveStatusChangeListenerDelegate>)delegate;
-(NSURL *)url;
-(unsigned long long)status;
-(FBMUServiceSession *)session;
@end

