/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBFeedToolbox, PAInterfaceGuide, NSArray, NSDictionary;

@interface FBNativeArticleComponentContext : NSObject {

	FBFeedToolbox* _toolbox;
	PAInterfaceGuide* _interfaceGuide;
	NSArray* _trackingCodes;
	NSDictionary* _analyticsInfo;

}

@property (nonatomic,__weak,readonly) FBFeedToolbox * toolbox;                 //@synthesize toolbox=_toolbox - In the implementation block
@property (nonatomic,readonly) PAInterfaceGuide * interfaceGuide;              //@synthesize interfaceGuide=_interfaceGuide - In the implementation block
@property (nonatomic,copy,readonly) NSArray * trackingCodes;                   //@synthesize trackingCodes=_trackingCodes - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * analyticsInfo;              //@synthesize analyticsInfo=_analyticsInfo - In the implementation block
-(FBFeedToolbox *)toolbox;
-(NSDictionary *)analyticsInfo;
-(NSArray *)trackingCodes;
-(PAInterfaceGuide *)interfaceGuide;
-(id)initWithToolbox:(id)arg1 interfaceGuide:(id)arg2 trackingCodes:(id)arg3 analyticsInfo:(id)arg4 ;
@end

