/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:38 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBNASharingOptionControlling.h>

@protocol FBNavigationCoordinator;
@class FBUserSession, FBAnalyticsInfo, NSURL, NSString;

@interface FBNASharingOptionSaveController : NSObject <FBNASharingOptionControlling> {

	id<FBNavigationCoordinator> _navigationCoordinatior;
	FBUserSession* _session;
	FBAnalyticsInfo* _analyticsInfo;
	NSURL* _preparedShareableURL;
	NSString* _saveState;

}

@property (nonatomic,retain) NSURL * preparedShareableURL;                                      //@synthesize preparedShareableURL=_preparedShareableURL - In the implementation block
@property (nonatomic,copy) NSString * saveState;                                                //@synthesize saveState=_saveState - In the implementation block
@property (nonatomic,readonly) id<FBNavigationCoordinator> navigationCoordinatior;              //@synthesize navigationCoordinatior=_navigationCoordinatior - In the implementation block
@property (nonatomic,readonly) FBUserSession * session;                                         //@synthesize session=_session - In the implementation block
@property (nonatomic,readonly) FBAnalyticsInfo * analyticsInfo;                                 //@synthesize analyticsInfo=_analyticsInfo - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy,readonly) NSString * actionTitle; 
@property (nonatomic,copy,readonly) NSString * actionDescription; 
@property (nonatomic,readonly) unsigned long long actionGlyphName; 
@property (nonatomic,copy,readonly) NSString * analyticsShareType; 
-(FBAnalyticsInfo *)analyticsInfo;
-(unsigned long long)actionGlyphName;
-(id)prepareActionWithShareable:(id)arg1 ;
-(id)initWithNavigationCoordinator:(id)arg1 session:(id)arg2 analyticsInfo:(id)arg3 ;
-(NSString *)actionDescription;
-(BOOL)canPerformActionWithShareable:(id)arg1 ;
-(id)performActionWithShareable:(id)arg1 ;
-(NSString *)analyticsShareType;
-(NSURL *)preparedShareableURL;
-(void)setPreparedShareableURL:(NSURL *)arg1 ;
-(void)setSaveState:(NSString *)arg1 ;
-(id<FBNavigationCoordinator>)navigationCoordinatior;
-(FBUserSession *)session;
-(NSString *)saveState;
-(NSString *)actionTitle;
@end

