/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:49 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Facebook/Facebook-Structs.h>
@class NSString;

@interface FBNavigationBarSearchTextTitleContext : NSObject {

	NSString* _titleText;
	NSRange _highlightedTextRange;

}

@property (nonatomic,copy,readonly) NSString * titleText;                 //@synthesize titleText=_titleText - In the implementation block
@property (nonatomic,readonly) NSRange highlightedTextRange;              //@synthesize highlightedTextRange=_highlightedTextRange - In the implementation block
-(id)initWithTitle:(id)arg1 highlightedTextRange:(NSRange)arg2 ;
-(NSRange)highlightedTextRange;
-(NSString *)titleText;
@end

