/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:36 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBNativeTemplateContext.h>

@protocol FBQueriedFeedUnitFieldsProtocol;
@class FBMemModelObject;

@interface FBNativeTemplateFeedContext : FBNativeTemplateContext {

	FBMemModelObject*<FBQueriedFeedUnitFieldsProtocol> _feedUnit;

}

@property (nonatomic,readonly) FBMemModelObject*<FBQueriedFeedUnitFieldsProtocol> feedUnit;              //@synthesize feedUnit=_feedUnit - In the implementation block
-(FBMemModelObject*<FBQueriedFeedUnitFieldsProtocol>)feedUnit;
-(id)initWithScenePath:(id)arg1 session:(id)arg2 navigationCoordinator:(id)arg3 intentHandler:(id)arg4 writeInterface:(id)arg5 cachedTemplates:(id)arg6 feedToolbox:(id)arg7 feedUnit:(id)arg8 ;
@end

