/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:43 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBNativeAppFeedCellWrapper : NSObject
+(id)headerImageFromDigitalGood:(id)arg1 ;
+(id)avatarImageFromDigitalGood:(id)arg1 ;
+(void)configureCell:(id)arg1 withDigitalGood:(id)arg2 indexPath:(id)arg3 delegate:(id)arg4 session:(id)arg5 ;
+(float)cellHeightWithDigitalGood:(id)arg1 withCellWidth:(float)arg2 ;
@end

