/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:34 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBReactionUnitReloaderProtocol.h>

@protocol FBNotificationsRichNotificationsUnitReloaderDelegate;
@class NSString;

@interface FBNotificationsRichNotificationsUnitReloader : NSObject <FBReactionUnitReloaderProtocol> {

	id<FBNotificationsRichNotificationsUnitReloaderDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<FBNotificationsRichNotificationsUnitReloaderDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)replaceUnit:(id)arg1 withUnit:(id)arg2 ;
-(void)reloadUnit:(id)arg1 withLocation:(id)arg2 ;
-(void)reloadUnit:(id)arg1 withLocation:(id)arg2 userInfo:(id)arg3 ;
-(void)setDelegate:(id<FBNotificationsRichNotificationsUnitReloaderDelegate>)arg1 ;
-(id<FBNotificationsRichNotificationsUnitReloaderDelegate>)delegate;
@end

