/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:30 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBExperimentContext.h>

@interface FBNotificationsRichNotificationsExperimentContext : FBExperimentContext {

	BOOL _enableNtInLiteQuery;
	BOOL _enableInlineComposerInCommentRichNotif;
	long long _expandedRichAttachmentLimit;
	BOOL _enableRichNotifications;

}

@property (assign,nonatomic) BOOL enableNtInLiteQuery;                                 //@synthesize enableNtInLiteQuery=_enableNtInLiteQuery - In the implementation block
@property (assign,nonatomic) BOOL enableInlineComposerInCommentRichNotif;              //@synthesize enableInlineComposerInCommentRichNotif=_enableInlineComposerInCommentRichNotif - In the implementation block
@property (assign,nonatomic) long long expandedRichAttachmentLimit;                    //@synthesize expandedRichAttachmentLimit=_expandedRichAttachmentLimit - In the implementation block
@property (assign,nonatomic) BOOL enableRichNotifications;                             //@synthesize enableRichNotifications=_enableRichNotifications - In the implementation block
+(id)universeName;
+(id)parameterConfigurations;
+(unsigned)mobileconfigConfigSpecifier;
+(id)configurationName;
-(void)logExposure;
-(BOOL)enableInlineComposerInCommentRichNotif;
-(BOOL)enableNtInLiteQuery;
-(BOOL)enableRichNotifications;
-(long long)expandedRichAttachmentLimit;
-(void)setEnableNtInLiteQuery:(BOOL)arg1 ;
-(void)setEnableInlineComposerInCommentRichNotif:(BOOL)arg1 ;
-(void)setExpandedRichAttachmentLimit:(long long)arg1 ;
-(void)setEnableRichNotifications:(BOOL)arg1 ;
@end

