/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:34 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBNotificationsRichNotificationsFieldsUpdateHelper : NSObject
+(void)_synchronousApplyNotifModificationWithNotifs:(id)arg1 connection:(id)arg2 notificationUpdateBlock:(/*^block*/id)arg3 ifPassesTest:(/*^block*/id)arg4 ;
+(void)changeRichAttachmentExpandedStateTo:(BOOL)arg1 forNotifications:(id)arg2 connection:(id)arg3 ;
+(void)replaceReactionUnitForNotification:(id)arg1 newUnit:(id)arg2 connection:(id)arg3 ;
@end

