/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:48 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBNuxBootstrapper : NSObject
+(void)setUpNuxCoordinatorForSession:(id)arg1 appModules:(id)arg2 navigationCoordinator:(id)arg3 ;
+(id)configurationProfileFromNuxPlistArray:(id)arg1 ;
+(void)setUpNuxCoordinatorForSession:(id)arg1 appModules:(id)arg2 navigationCoordinator:(id)arg3 nuxCatalog:(id)arg4 nuxPersistentStore:(id)arg5 eligibilityFetchRunner:(id)arg6 ;
+(id)_nuxPresentersFromAppModules:(id)arg1 session:(id)arg2 ;
@end

