/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:31 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSDate, NSString;

@interface FBPageCTAContactUsRequestModel : NSObject <NSCopying> {

	unsigned long long _subtype;
	NSDate* _fBPageRequestExpirationModel_date;
	NSString* _fBPageRequestBodyTextModel_name;
	NSString* _fBPageRequestBodyTextModel_date;
	NSString* _fBPageRequestBodyTextModel_bodyText;
	NSString* _fBPageRequestEmailModel_email;
	NSString* _fBPageRequestPhoneModel_displayNumber;
	NSString* _fBPageRequestPhoneModel_universalNumber;
	BOOL _fBPageMarkAsRespondedModel_selected;

}
+(id)fBPageRequestExpirationModelWithDate:(id)arg1 ;
+(id)fBPageRequestBodyTextModelWithName:(id)arg1 date:(id)arg2 bodyText:(id)arg3 ;
+(id)fBPageRequestEmailModelWithEmail:(id)arg1 ;
+(id)fBPageRequestPhoneModelWithDisplayNumber:(id)arg1 universalNumber:(id)arg2 ;
+(id)fBPageMarkAsRespondedModelWithSelected:(BOOL)arg1 ;
+(id)fBPageRequestReportModel;
-(void)matchFBPageRequestExpirationModel:(/*^block*/id)arg1 fBPageRequestBodyTextModel:(/*^block*/id)arg2 fBPageRequestEmailModel:(/*^block*/id)arg3 fBPageRequestPhoneModel:(/*^block*/id)arg4 fBPageMarkAsRespondedModel:(/*^block*/id)arg5 fBPageRequestReportModel:(/*^block*/id)arg6 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

