/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:42 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface FBPageComponentFlowFunnelLogger : NSObject {

	NSString* _flowType;
	NSString* _entryEntId;
	NSString* _referrer;

}

@property (nonatomic,copy,readonly) NSString * funnelName; 
-(void)startFunnel;
-(void)endFunnel;
-(void)addFunnelTag:(id)arg1 ;
-(NSString *)funnelName;
-(void)addAction:(id)arg1 withTag:(id)arg2 ;
-(void)addAction:(id)arg1 withExtra:(id)arg2 ;
-(id)initWithFlowType:(id)arg1 entryEntId:(id)arg2 referrer:(id)arg3 ;
-(void)addAction:(id)arg1 ;
@end

