/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:43 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBPaymentsSectionBasedTableViewController.h>
#import <Facebook/FBPaymentsContactInfoSectionDelegate.h>

@protocol FBPaymentsContactInfoListViewControllerDelegate;
@class FBUserSession, FBPaymentsContactInfoSection, NSString;

@interface FBPaymentsContactInfoListViewController : FBPaymentsSectionBasedTableViewController <FBPaymentsContactInfoSectionDelegate> {

	FBUserSession* _session;
	FBPaymentsContactInfoSection* _emailAddressSection;
	FBPaymentsContactInfoSection* _phoneNumberSection;
	BOOL _emailDataLoaded;
	BOOL _phoneDataLoaded;
	BOOL _shouldEnableSelection;
	BOOL _shouldHideEmailSection;
	BOOL _shouldHidePhoneSection;
	BOOL _shouldHideSectionHeader;
	id _selectedContactEmail;
	id _selectedContactPhone;
	id<FBPaymentsContactInfoListViewControllerDelegate> _delegate;

}

@property (assign,nonatomic) BOOL shouldEnableSelection;                                                       //@synthesize shouldEnableSelection=_shouldEnableSelection - In the implementation block
@property (assign,nonatomic) BOOL shouldHideEmailSection;                                                      //@synthesize shouldHideEmailSection=_shouldHideEmailSection - In the implementation block
@property (assign,nonatomic) BOOL shouldHidePhoneSection;                                                      //@synthesize shouldHidePhoneSection=_shouldHidePhoneSection - In the implementation block
@property (nonatomic,copy) id selectedContactEmail;                                                            //@synthesize selectedContactEmail=_selectedContactEmail - In the implementation block
@property (nonatomic,copy) id selectedContactPhone;                                                            //@synthesize selectedContactPhone=_selectedContactPhone - In the implementation block
@property (assign,nonatomic) BOOL shouldHideSectionHeader;                                                     //@synthesize shouldHideSectionHeader=_shouldHideSectionHeader - In the implementation block
@property (assign,nonatomic,__weak) id<FBPaymentsContactInfoListViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)fb_showNavBarSearchField;
-(BOOL)fb_hideNavBarRightButton;
-(void)setShouldHideSectionHeader:(BOOL)arg1 ;
-(BOOL)shouldHideSectionHeader;
-(id)newNavigationController;
-(void)setShouldEnableSelection:(BOOL)arg1 ;
-(void)setShouldHidePhoneSection:(BOOL)arg1 ;
-(void)setShouldHideEmailSection:(BOOL)arg1 ;
-(void)setSelectedContactEmail:(id)arg1 ;
-(void)setSelectedContactPhone:(id)arg1 ;
-(BOOL)shouldEnableSelection;
-(void)_setTableViewSections;
-(void)_setBackgroundColor;
-(void)contactInfoSection:(id)arg1 didSelectContactData:(id)arg2 ;
-(void)contactInfoSectionDidLoadContactData:(id)arg1 ;
-(BOOL)shouldHideEmailSection;
-(BOOL)shouldHidePhoneSection;
-(id)selectedContactEmail;
-(id)selectedContactPhone;
-(void)setDelegate:(id<FBPaymentsContactInfoListViewControllerDelegate>)arg1 ;
-(id<FBPaymentsContactInfoListViewControllerDelegate>)delegate;
-(void)viewDidLoad;
-(id)initWithSession:(id)arg1 ;
-(id)viewControllerForPresenting;
-(void)_setTitle;
@end

