/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:42 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBPaymentsSettingsSectionExtension <FBPaymentsSettingsExtensionPreviewingHandler,FBPaymentsTableViewSection>
@property (assign,nonatomic,__weak) id<FBModalWebFlowDelegate> modalWebFlowDelegate; 
@optional
-(id)sectionFooterViewModel;
-(id)rightAccessoryViewForSectionHeader;

@required
-(BOOL)shouldHighlightCellForRowAtIndex:(unsigned long long)arg1;
-(void)commitEditingStyle:(long long)arg1 forRowAtRowIndex:(unsigned long long)arg2;
-(id)titleForDeleteConfirmationButtonForRowAtIndex:(unsigned long long)arg1;
-(unsigned long long)interestedDataTypes;
-(id<FBModalWebFlowDelegate>)modalWebFlowDelegate;
-(void)setModalWebFlowDelegate:(id)arg1;
-(void)tearDown;
-(long long)editingStyleForRowAtIndex:(unsigned long long)arg1;

@end

