/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:31 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBTableViewController.h>
#import <Facebook/FBEmbeddedTab.h>

@class FBMemPage, FBUserSession, NSString, NSArray, UIView, UIScrollView;

@interface FBPageMoreChildLocationsController : FBTableViewController <FBEmbeddedTab> {

	FBMemPage* _page;
	FBUserSession* _session;
	NSString* _analyticsUUID;
	NSArray* _childLocationsInfo;
	UIView* _stickyHeaderView;

}

@property (nonatomic,readonly) UIScrollView * scrollView; 
@property (nonatomic,retain) UIView * secondaryStickyHeaderView; 
-(id)analyticsModule;
-(BOOL)fb_showNavBarSearchField;
-(BOOL)fb_showBackArrowButton;
-(void)refreshData;
-(BOOL)shouldApplyTabBarContentInsets;
-(UIView *)secondaryStickyHeaderView;
-(void)_fetchChildLocations;
-(void)didDownloadPage:(id)arg1 isCached:(BOOL)arg2 error:(id)arg3 ;
-(id)initWithPage:(id)arg1 session:(id)arg2 analyticsUUID:(id)arg3 stickyHeaderView:(id)arg4 ;
-(double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(unsigned long long)supportedInterfaceOrientations;
-(UIScrollView *)scrollView;
-(long long)preferredInterfaceOrientationForPresentation;
-(void)viewDidLoad;
@end

