/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBPhotoViewerProvider : NSObject
+(id)photoViewerWithSession:(id)arg1 photoStoryContainer:(id)arg2 focusedCommentID:(id)arg3 composerActivationSource:(id)arg4 openInTaggingMode:(BOOL)arg5 openInDimmedMode:(BOOL)arg6 darkThemePresentationMode:(long long)arg7 dimmingTimerInterval:(long long)arg8 photoViewProvider:(id)arg9 trackingCodes:(id)arg10 extraAnalyticsData:(id)arg11 ;
@end

