/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:39 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>

@protocol FBEventTimePickerControllerDelegate;
@class FBPopoverEventTimePickerEditTimeCell, UITableViewCell, UISwitch, NSDateFormatter, UITableView, NSDate, NSString;

@interface FBPopoverEventTimePickerViewController : UIViewController <UITableViewDelegate, UITableViewDataSource> {

	BOOL _allDay;
	FBPopoverEventTimePickerEditTimeCell* _startTimeCell;
	FBPopoverEventTimePickerEditTimeCell* _endTimeCell;
	UITableViewCell* _allDayCell;
	UISwitch* _allDaySwitch;
	NSDateFormatter* _dateFormatter;
	NSDateFormatter* _timeFormatter;
	UITableView* _tableView;
	id<FBEventTimePickerControllerDelegate> _delegate;
	NSDate* _startTime;
	NSDate* _endTime;

}

@property (nonatomic,retain) NSDate * startTime;                                                   //@synthesize startTime=_startTime - In the implementation block
@property (nonatomic,retain) NSDate * endTime;                                                     //@synthesize endTime=_endTime - In the implementation block
@property (assign,nonatomic,__weak) id<FBEventTimePickerControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_didTapCancel:(id)arg1 ;
-(void)_didTapDone:(id)arg1 ;
-(void)_showInvalidTimeAlert;
-(void)_setupCells;
-(id)initWithStartTime:(id)arg1 endTime:(id)arg2 allDay:(BOOL)arg3 ;
-(void)_didTapStartDate:(id)arg1 ;
-(void)_didTapStartTime:(id)arg1 ;
-(void)_didTapEndDate:(id)arg1 ;
-(void)_didTapEndTime:(id)arg1 ;
-(void)_startDateChanged:(id)arg1 ;
-(void)_presentPopoverWithViewController:(id)arg1 inView:(id)arg2 ;
-(void)_startTimeChanged:(id)arg1 ;
-(void)_endDateChanged:(id)arg1 ;
-(void)_setInitialEndTime;
-(void)_endTimeChanged:(id)arg1 ;
-(id)_generateTimeFrom:(id)arg1 dateFrom:(id)arg2 ;
-(void)setDelegate:(id<FBEventTimePickerControllerDelegate>)arg1 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(id<FBEventTimePickerControllerDelegate>)delegate;
-(void)setStartTime:(NSDate *)arg1 ;
-(void)viewDidLoad;
-(NSDate *)startTime;
-(NSDate *)endTime;
-(void)setEndTime:(NSDate *)arg1 ;
-(void)_switchValueChanged:(id)arg1 ;
@end

