/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:36 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBAssetsLibraryListener.h>

@protocol FBProfileRankedPhotosControllerDelegate;
@class FBUserSession, FBAssetsLibrary, NSMutableArray, NSString;

@interface FBProfileRankedPhotosController : NSObject <FBAssetsLibraryListener> {

	FBUserSession* _session;
	BOOL _shouldDoFaceRec;
	long long _kValue;
	FBAssetsLibrary* _assetsLibrary;
	id<FBProfileRankedPhotosControllerDelegate> delegate;
	NSMutableArray* inputAssetsArray;
	NSMutableArray* classifierInputsArray;

}

@property (assign,nonatomic,__weak) id<FBProfileRankedPhotosControllerDelegate> delegate; 
@property (nonatomic,retain) NSMutableArray * inputAssetsArray; 
@property (nonatomic,retain) NSMutableArray * classifierInputsArray; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)assetsLibraryDidLoadAssets;
-(void)prepareRankedPhotosAssets;
-(NSMutableArray *)inputAssetsArray;
-(NSMutableArray *)classifierInputsArray;
-(void)setInputAssetsArray:(NSMutableArray *)arg1 ;
-(void)setClassifierInputsArray:(NSMutableArray *)arg1 ;
-(void)prepareAssetsWithCompletion:(/*^block*/id)arg1 ;
-(id)_assetDetailsForClassifierInput:(id)arg1 assetsToFaceFeatures:(id)arg2 imageAttributeIndex:(id)arg3 faceDetectionIndex:(id)arg4 ;
-(void)getFaceFeaturesWithAssets:(id)arg1 imageAttributeIndex:(id)arg2 faceDetectionIndex:(id)arg3 withCompletion:(/*^block*/id)arg4 ;
-(void)setDelegate:(id<FBProfileRankedPhotosControllerDelegate>)arg1 ;
-(id<FBProfileRankedPhotosControllerDelegate>)delegate;
-(id)initWithSession:(id)arg1 ;
@end

