/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:39 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <Facebook/CKComponentHostingViewDelegate.h>
#import <Facebook/FBPrivacyCheckupViewControllerDelegate.h>

@class CKComponentHostingView, FBUserSession, FBPrivacyCheckupViewController, NSString, UIScrollView, NSNumber;

@interface FBPrivacyCheckupInterstitialViewController : UIViewController <CKComponentHostingViewDelegate, FBPrivacyCheckupViewControllerDelegate> {

	CKComponentHostingView* _hostingView;
	FBUserSession* _session;
	FBPrivacyCheckupViewController* _privacyCheckupViewController;
	BOOL _showingConfirmationView;
	NSString* _source;
	UIScrollView* _scrollView;
	NSNumber* _sessionID;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)componentForModel:(id)arg1 context:(id)arg2 ;
-(void)componentHostingViewDidInvalidateSize:(id)arg1 ;
-(void)didTapDoneButton:(id)arg1 ;
-(void)didTapCancelButton:(id)arg1 ;
-(void)_appWillResign;
-(id)initWithSession:(id)arg1 forSource:(id)arg2 ;
-(void)didTapContinueButton:(id)arg1 ;
-(void)privacyCheckupViewControllerDidTapCancel:(id)arg1 ;
-(void)privacyCheckupViewControllerDidTapDone:(id)arg1 ;
-(void)dealloc;
-(unsigned long long)supportedInterfaceOrientations;
-(void)viewDidLayoutSubviews;
-(long long)preferredInterfaceOrientationForPresentation;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
@end

