/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:36 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>
#import <Facebook/FBHScrollImpressionLogging.h>

@class NSString, NSArray, FBMemPagesYouMayAdvertiseFeedUnitItem, NSNumber, FBFeedToolbox;

@interface FBPYMAFeedUnitItemComponent : CKCompositeComponent <FBHScrollImpressionLogging> {

	NSString* _unitCacheId;
	NSArray* _trackingCodes;
	FBMemPagesYouMayAdvertiseFeedUnitItem* _item;
	NSNumber* _index;
	NSString* _category;
	FBFeedToolbox* _toolbox;

}
+(id)newWithItem:(id)arg1 promoteCTAText:(id)arg2 options:(const FBPYMAFeedUnitItemComponentOptions*)arg3 itemIndex:(id)arg4 unitCacheId:(id)arg5 category:(id)arg6 toolbox:(id)arg7 ;
-(void)becameFullyVisible;
@end

