/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:54 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBQueriedNativeComponentFlowRequestFieldsProtocol
@required
-(id)graphQLID;
-(id)bookingStatus;
-(id)requestedTime;
-(id)serviceGeneralInfo;
-(id)specialRequest;
-(id)suggestedTimeRange;
-(id)userAvailability;
-(id)user;
-(id)page;
-(id)status;
-(id)productItem;

@end

