/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:42 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>

@class FBRapidReportingTextViewComponent;

@interface FBRapidReportingInputComponent : CKCompositeComponent {

	FBRapidReportingTextViewComponent* _textViewComponent;

}

@property (nonatomic,readonly) FBRapidReportingTextViewComponent * textViewComponent;              //@synthesize textViewComponent=_textViewComponent - In the implementation block
+(id)newWithMetadata:(id)arg1 helpAction:(CKTypedComponentAction<>)arg2 didSelectTagAction:(CKTypedComponentAction<>)arg3 textDidChangeAction:(CKTypedComponentAction<>)arg4 uiProvider:(id)arg5 ;
-(FBRapidReportingTextViewComponent *)textViewComponent;
@end

