/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:35 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/CKCompositeComponent.h>

@class NSString, FBLocalReviewDetailsStoryComponentContext;

@interface FBRatingsReviewsVPVdLoggingWrappingComponent : CKCompositeComponent {

	NSString* _unitType;
	NSString* _unitIdentifier;
	FBLocalReviewDetailsStoryComponentContext* _context;

}

@property (nonatomic,readonly) FBLocalReviewDetailsStoryComponentContext * context;              //@synthesize context=_context - In the implementation block
@property (nonatomic,copy,readonly) NSString * unitType;                                         //@synthesize unitType=_unitType - In the implementation block
@property (nonatomic,copy,readonly) NSString * unitIdentifier;                                   //@synthesize unitIdentifier=_unitIdentifier - In the implementation block
+(id)newWithComponent:(id)arg1 context:(id)arg2 unitType:(id)arg3 unitIdentifier:(id)arg4 ;
-(NSString *)unitIdentifier;
-(FBLocalReviewDetailsStoryComponentContext *)context;
-(NSString *)unitType;
@end

