/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:51 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/RCTViewManager.h>

@class NSHashTable;

@interface FBReactNoBackSwipeViewManager : RCTViewManager {

	NSHashTable* _viewsWithDisabledBackSwipe;

}
+(id)moduleName;
+(id)propConfig_enabled;
+(void)load;
-(BOOL)shouldBeginBackSwipeAtPoint:(CGPoint)arg1 inView:(id)arg2 ;
-(void)set_enabled:(id)arg1 forView:(id)arg2 withDefaultView:(id)arg3 ;
-(void)setBackSwipeDisbled:(BOOL)arg1 forView:(id)arg2 ;
-(void)setBridge:(id)arg1 ;
@end

