/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:01:00 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <UIKit/UIView.h>

@class UIColor;

@interface FBRectangleWithRoundedCornerView : UIView {

	double _rectangleCornerRadius;
	unsigned long long _rectCorner;
	UIColor* _color;

}

@property (nonatomic,retain) UIColor * color;                            //@synthesize color=_color - In the implementation block
@property (assign,nonatomic) double rectangleCornerRadius;               //@synthesize rectangleCornerRadius=_rectangleCornerRadius - In the implementation block
@property (assign,nonatomic) unsigned long long rectCorner;              //@synthesize rectCorner=_rectCorner - In the implementation block
-(id)initWithCornerRadius:(double)arg1 color:(id)arg2 rectCorner:(unsigned long long)arg3 ;
-(void)setRectangleCornerRadius:(double)arg1 ;
-(void)setRectCorner:(unsigned long long)arg1 ;
-(double)rectangleCornerRadius;
-(unsigned long long)rectCorner;
-(void)drawRect:(CGRect)arg1 ;
-(UIColor *)color;
-(void)setColor:(UIColor *)arg1 ;
@end

