/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:34 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBReactionUnitComponentAdapterDelegate <NSObject>
@optional
-(id)currentPageId;
-(void)parentComponentShouldHighlight:(BOOL)arg1 forUnitComponentAdapter:(id)arg2;
-(void)scrollToNextCardComponentWithCurrentUnitComponentAdapter:(id)arg1;
-(void)scrollToUnit:(id)arg1 forReactionUnitComponentAdapter:(id)arg2;
-(void)triggerDownloadAllUnitsFromUnitComponentAdapter:(id)arg1;

@required
-(void)switchToNewOverlayWithPageId:(id)arg1;
-(void)hideUnitForUnitComponentAdapter:(id)arg1;
-(void)replaceUnit:(id)arg1 withUnit:(id)arg2 forUnitComponentAdapter:(id)arg3;
-(void)hideCardComponentContainingReactionUnitComponentAdapter:(id)arg1;
-(void)updateComponentForUnitComponentAdapter:(id)arg1 oldComponentView:(id)arg2;
-(void)hideComponentForUnitComponentAdapter:(id)arg1;
-(void)heightDidChangeForUnitComponentAdapter:(id)arg1 shouldPreservePosition:(BOOL)arg2;

@end

