/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:43 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@protocol FBQueriedReactionUnitFieldsProtocol;
@class FBMemModelObject, FBReactionContext;

@interface FBReactionUnitDataModel : FBValueObject <NSCopying> {

	FBMemModelObject*<FBQueriedReactionUnitFieldsProtocol> _unit;
	FBReactionContext* _context;

}

@property (nonatomic,copy,readonly) FBMemModelObject*<FBQueriedReactionUnitFieldsProtocol> unit;              //@synthesize unit=_unit - In the implementation block
@property (nonatomic,readonly) FBReactionContext * context;                                                   //@synthesize context=_context - In the implementation block
-(id)initWithUnit:(id)arg1 context:(id)arg2 ;
-(FBReactionContext *)context;
-(FBMemModelObject*<FBQueriedReactionUnitFieldsProtocol>)unit;
@end

