/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:34 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>

@protocol FBReactionPhotoGridComponentDelegate;
@class NSArray, FBFeedToolbox;

@interface FBReactionPhotoGridComponent : CKCompositeComponent {

	NSArray* _photos;
	FBFeedToolbox* _toolbox;
	id<FBReactionPhotoGridComponentDelegate> _delegate;
	vector<FBCollageLayoutComponentChild, std::__1::allocator<FBCollageLayoutComponentChild> >* _children;
	CKTypedComponentAction<> _alternateTapAction;

}

@property (assign,nonatomic) vector<FBCollageLayoutComponentChild children;                         //@synthesize children=_children - In the implementation block
@property (nonatomic,copy) NSArray * photos;                                                        //@synthesize photos=_photos - In the implementation block
@property (nonatomic,retain) FBFeedToolbox * toolbox;                                               //@synthesize toolbox=_toolbox - In the implementation block
@property (assign,nonatomic,__weak) id<FBReactionPhotoGridComponentDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) CKTypedComponentAction<> alternateTapAction;                           //@synthesize alternateTapAction=_alternateTapAction - In the implementation block
+(id)newWithPhotoAttachments:(id)arg1 toolbox:(id)arg2 insets:(UIEdgeInsets)arg3 delegate:(id)arg4 alternateTapAction:(CKTypedComponentAction<>)arg5 ;
-(FBFeedToolbox *)toolbox;
-(void)setToolbox:(FBFeedToolbox *)arg1 ;
-(void)setAlternateTapAction:(CKTypedComponentAction<>)arg1 ;
-(CKTypedComponentAction<>)alternateTapAction;
-(void)setDelegate:(id<FBReactionPhotoGridComponentDelegate>)arg1 ;
-(id<FBReactionPhotoGridComponentDelegate>)delegate;
-(void)setPhotos:(NSArray *)arg1 ;
-(NSArray *)photos;
-(void)setChildren:(vector<FBCollageLayoutComponentChild)arg1 ;
-(vector<FBCollageLayoutComponentChild)children;
@end

