/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBResearchPollLogHelper : NSObject
+(void)logActionForSurvey:(id)arg1 interactionType:(id)arg2 currentQuestion:(id)arg3 answerIndex:(id)arg4 ;
+(id)extraParamsForSurvey:(id)arg1 interactionType:(id)arg2 currentQuestion:(id)arg3 answerIndex:(id)arg4 ;
+(void)logPollLoaded:(id)arg1 ;
+(void)logPollOpened:(id)arg1 ;
+(void)logSurvey:(id)arg1 question:(id)arg2 responseIndex:(unsigned long long)arg3 didSelect:(BOOL)arg4 ;
+(void)logPoll:(id)arg1 didVoteQuestion:(id)arg2 ;
+(void)logPollCompleted:(id)arg1 ;
@end

