/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:50 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBExperimentContext.h>

@interface FBRtcVideoQualityUniExperimentContext : FBExperimentContext {

	int __v;
	int _bins;
	int _enable_h264;
	int _enable_vp8;
	int _log;
	int _skip;
	int _subbands;

}

@property (nonatomic,readonly) int _v;                       //@synthesize _v=__v - In the implementation block
@property (nonatomic,readonly) int bins;                     //@synthesize bins=_bins - In the implementation block
@property (nonatomic,readonly) int enable_h264;              //@synthesize enable_h264=_enable_h264 - In the implementation block
@property (nonatomic,readonly) int enable_vp8;               //@synthesize enable_vp8=_enable_vp8 - In the implementation block
@property (nonatomic,readonly) int log;                      //@synthesize log=_log - In the implementation block
@property (nonatomic,readonly) int skip;                     //@synthesize skip=_skip - In the implementation block
@property (nonatomic,readonly) int subbands;                 //@synthesize subbands=_subbands - In the implementation block
+(id)universeName;
+(id)parameterConfigurations;
-(int)enable_h264;
-(int)enable_vp8;
-(int)subbands;
-(int)_v;
-(int)log;
-(int)skip;
-(int)bins;
@end

