/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:42 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Facebook/Facebook-Structs.h>
@class FBUserSession, NSString;

@interface FBSecurityCheckupContext : NSObject {

	BOOL _shouldShowStatusBar;
	FBUserSession* _userSession;
	NSString* _source;
	CGSize _containingViewSize;

}

@property (nonatomic,retain) FBUserSession * userSession;              //@synthesize userSession=_userSession - In the implementation block
@property (nonatomic,copy) NSString * source;                          //@synthesize source=_source - In the implementation block
@property (assign,nonatomic) CGSize containingViewSize;                //@synthesize containingViewSize=_containingViewSize - In the implementation block
@property (assign,nonatomic) BOOL shouldShowStatusBar;                 //@synthesize shouldShowStatusBar=_shouldShowStatusBar - In the implementation block
-(BOOL)shouldShowStatusBar;
-(id)initWithUserSession:(id)arg1 source:(id)arg2 containingViewSize:(CGSize)arg3 shouldShowStatusBar:(BOOL)arg4 ;
-(CGSize)containingViewSize;
-(void)setContainingViewSize:(CGSize)arg1 ;
-(void)setShouldShowStatusBar:(BOOL)arg1 ;
-(void)setSource:(NSString *)arg1 ;
-(NSString *)source;
-(FBUserSession *)userSession;
-(void)setUserSession:(FBUserSession *)arg1 ;
@end

