/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:32 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/FBSearchResultsStoryLoggingHandlerProtocol.h>

@class NSMutableDictionary, FBSearchResultsStoryProxyingIntentHandler, FBSearchResultsFeedEventBusProvider, FBSearchResultsStoryFeedComponentEventListener, FBSearchResultsContext;

@interface FBSearchResultsStoryLoggingManager : NSObject <FBSearchResultsStoryLoggingHandlerProtocol> {

	NSMutableDictionary* _storyIdToStoryEdgeModelMap;
	FBSearchResultsStoryProxyingIntentHandler* _proxyingIntentHandler;
	FBSearchResultsFeedEventBusProvider* _eventBusProvider;
	FBSearchResultsStoryFeedComponentEventListener* _feedComponentEventListener;
	FBSearchResultsContext* _searchResultsContext;

}

@property (nonatomic,readonly) FBSearchResultsStoryProxyingIntentHandler * proxyingIntentHandler;                        //@synthesize proxyingIntentHandler=_proxyingIntentHandler - In the implementation block
@property (nonatomic,readonly) FBSearchResultsFeedEventBusProvider * eventBusProvider;                                   //@synthesize eventBusProvider=_eventBusProvider - In the implementation block
@property (nonatomic,readonly) FBSearchResultsStoryFeedComponentEventListener * feedComponentEventListener;              //@synthesize feedComponentEventListener=_feedComponentEventListener - In the implementation block
@property (assign,nonatomic,__weak) FBSearchResultsContext * searchResultsContext;                                       //@synthesize searchResultsContext=_searchResultsContext - In the implementation block
-(void)storyEdgeModel:(id)arg1 didTriggerAction:(id)arg2 ;
-(void)_setFeedStoryTrackingForModel:(id)arg1 ;
-(id)_storyIdForStoryEdgeModel:(id)arg1 ;
-(void)_logStoryEdgeModel:(id)arg1 action:(id)arg2 extra:(id)arg3 ;
-(void)storyWithAnalyticsInfo:(id)arg1 didTriggerAction:(id)arg2 extra:(id)arg3 debugInfo:(id)arg4 ;
-(void)setSearchResultsContext:(FBSearchResultsContext *)arg1 ;
-(FBSearchResultsContext *)searchResultsContext;
-(id)feedStoryTrackingDataForDisablingTracking;
-(FBSearchResultsFeedEventBusProvider *)eventBusProvider;
-(id)feedStoryTrackingDataForStoryEdgeModel:(id)arg1 ;
-(FBSearchResultsStoryFeedComponentEventListener *)feedComponentEventListener;
-(void)buildStoryLoggingMapForChangeset:(const Changeset*)arg1 ;
-(id)initWithTargetIntentHandler:(id)arg1 ;
-(FBSearchResultsStoryProxyingIntentHandler *)proxyingIntentHandler;
@end

