/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:32 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>

@class CKComponent, NSString, FBSearchResultsContext;

@interface FBSearchResultsDebateSentimentReactionIconComponent : CKCompositeComponent {

	CKTypedComponentAction<> _voteAction;
	CKComponent* _icon;
	NSString* _reactionID;
	FBSearchResultsContext* _context;

}

@property (nonatomic,retain) FBSearchResultsContext * context;              //@synthesize context=_context - In the implementation block
+(id)newWithReaction:(id)arg1 context:(id)arg2 action:(CKTypedComponentAction<>)arg3 ;
-(void)iconPressed:(id)arg1 ;
-(FBSearchResultsContext *)context;
-(void)setContext:(FBSearchResultsContext *)arg1 ;
@end

