/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:41 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Facebook/Facebook-Structs.h>
@interface FBSearchResultsLinkComponentHelper : NSObject
+(void)didTap:(id)arg1 linkEdgeModel:(id)arg2 openPulse:(BOOL)arg3 context:(id)arg4 ;
+(id)thumbnailComponent:(id)arg1 context:(id)arg2 size:(CGSize)arg3 ;
+(id)_instantArticleIntentFromExternalURL:(id)arg1 ;
@end

