/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:40 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/FBShareSheetTargetCell.h>
#import <Facebook/CKComponentProvider.h>
#import <Facebook/CKComponentHostingViewDelegate.h>

@protocol FBShareSheetFeedDestinationCellDelegate;
@class UILabel, CKComponentHostingView, NSString;

@interface FBShareSheetFeedDestinationCell : FBShareSheetTargetCell <CKComponentProvider, CKComponentHostingViewDelegate> {

	UILabel* _privacyLabel;
	CKComponentHostingView* _pillComponent;
	CKTypedComponentAction<> _privacyPillAction;
	id<FBShareSheetFeedDestinationCellDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<FBShareSheetFeedDestinationCellDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)componentForModel:(id)arg1 context:(id)arg2 ;
-(void)componentHostingViewDidInvalidateSize:(id)arg1 ;
-(void)setupCell;
-(void)setChecked:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setPrivacy:(id)arg1 toolbox:(id)arg2 ;
-(void)setDelegate:(id<FBShareSheetFeedDestinationCellDelegate>)arg1 ;
-(void)layoutSubviews;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(id<FBShareSheetFeedDestinationCellDelegate>)delegate;
@end

