/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:50 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <UIKit/UIControl.h>
#import <Facebook/FBNuxTooltipViewDelegate.h>

@class CAShapeLayer, FBNuxTooltipView, NSString;

@interface FBSimpleTooltipView : UIControl <FBNuxTooltipViewDelegate> {

	CAShapeLayer* _bubbleShapeLayer;
	FBNuxTooltipView* _nuxContentView;
	/*^block*/id _dismissBlock;
	double _arrowOffset;
	double _scaleAmount;
	CGPoint _arrowPosition;
	UIEdgeInsets _hitTestSlop;

}

@property (nonatomic,copy,readonly) NSString * titleText; 
@property (nonatomic,copy,readonly) NSString * descriptionText; 
@property (assign,nonatomic) CGPoint arrowPosition;                          //@synthesize arrowPosition=_arrowPosition - In the implementation block
@property (assign,nonatomic) double arrowOffset;                             //@synthesize arrowOffset=_arrowOffset - In the implementation block
@property (assign,nonatomic) double scaleAmount;                             //@synthesize scaleAmount=_scaleAmount - In the implementation block
@property (assign,nonatomic) UIEdgeInsets hitTestSlop;                       //@synthesize hitTestSlop=_hitTestSlop - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)initialize;
-(void)setHitTestSlop:(UIEdgeInsets)arg1 ;
-(void)setArrowPosition:(CGPoint)arg1 ;
-(id)initWithTitleText:(id)arg1 descriptionText:(id)arg2 dismissBlock:(/*^block*/id)arg3 ;
-(void)setScaleAmount:(double)arg1 ;
-(UIEdgeInsets)hitTestSlop;
-(void)_didTapBubble:(id)arg1 ;
-(void)tooltipViewDidTapCancelButton:(id)arg1 ;
-(CGPoint)arrowPosition;
-(double)scaleAmount;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id)initWithText:(id)arg1 ;
-(void)setArrowOffset:(double)arg1 ;
-(double)arrowOffset;
-(NSString *)descriptionText;
-(NSString *)titleText;
@end

