/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:45 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
#import <Facebook/Facebook-Structs.h>
@class FBUserSession, NSHashTable, NSObject, FBStorylineMoodsData, FBStorylineMoodValidator;

@interface FBStorylineMoodsManager : NSObject {

	FBUserSession* _session;
	BOOL _isProcessing;
	recursive_mutex _subscriptionlock;
	NSHashTable* _subscriptions;
	NSObject*<OS_dispatch_queue> _serialPerformer;
	NSObject*<OS_dispatch_queue> _trackDownloadPerformer;
	NSObject*<OS_dispatch_queue> _assetsDownloadPerformer;
	FBStorylineMoodsData* _moodsData;
	FBStorylineMoodValidator* _validator;

}

@property (readonly) FBStorylineMoodsData * moodsData; 
@property (nonatomic,readonly) BOOL initialDataLoaded; 
-(void)unsubscribe:(id)arg1 ;
-(void)_prefetchAssets;
-(id)moodTypeByMoodId:(id)arg1 ;
-(id)moodIconURIByMoodId:(id)arg1 ;
-(id)moodNameByMoodId:(id)arg1 ;
-(BOOL)initialDataLoaded;
-(id)moodAssetsMapByMoodId:(id)arg1 ;
-(id)musicTacksByMoodId:(id)arg1 ;
-(FBStorylineMoodsData *)moodsData;
-(void)lazyStart;
-(void)refreshIfNecessary;
-(void)prefetchAudioRenderTrack:(id)arg1 ;
-(id)subscribe:(id)arg1 performer:(id)arg2 ;
-(id)_getVersionedMoodsCacheKey;
-(void)_clearOldMoodsCache;
-(void)_processWithTTL:(double)arg1 ;
-(void)_downloadTracks;
-(BOOL)_reanderTrackNeedDownload:(id)arg1 ;
-(void)_updateData:(id)arg1 ;
-(void)_fetchQuery:(/*^block*/id)arg1 ;
-(id)_parseMoodData:(id)arg1 error:(id*)arg2 ;
-(BOOL)_trackNeedDownload:(id)arg1 ;
-(id)_shuffleMoods:(id)arg1 ;
-(void)downloadTracks;
-(id)_audioFileURLForName:(id)arg1 ;
-(void)start;
-(id)initWithSession:(id)arg1 ;
@end

