/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:40 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBStreamingEventEntitySubscriber.h>

@protocol FBGraphQLSubscriptionHandle;
@class FBUserSession, NSString;

@interface FBStreamingEventDonatePushSubscriber : NSObject <FBStreamingEventEntitySubscriber> {

	id<FBGraphQLSubscriptionHandle> _subscriptionHandle;
	/*^block*/id _successHandler;
	FBUserSession* _session;
	NSString* _videoID;

}

@property (nonatomic,retain) FBUserSession * session;               //@synthesize session=_session - In the implementation block
@property (nonatomic,copy) NSString * videoID;                      //@synthesize videoID=_videoID - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSString *)videoID;
-(id)_graphQLQuery;
-(id)initWithSession:(id)arg1 videoID:(id)arg2 ;
-(void)setVideoID:(NSString *)arg1 ;
-(void)stopSubscription;
-(void)_processEventsFromPayload:(id)arg1 ;
-(void)startSubscriptionWithSuccessBlock:(/*^block*/id)arg1 ;
-(unsigned long long)type;
-(FBUserSession *)session;
-(void)setSession:(FBUserSession *)arg1 ;
@end

