/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:39 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBStorylineEmbeddedPickerViewDelegate <NSObject>
@optional
-(void)storylineEmbeddedPickerViewPermissionGranted:(id)arg1;
-(void)storylineEmbeddedPickerViewDidShowPermissionView:(id)arg1;
-(void)storylineEmbeddedPickerView:(id)arg1 didScroll:(id)arg2;
-(void)storylineEmbeddedPickerView:(id)arg1 scrollViewDidEndDecelerating:(id)arg2;

@required
-(void)storylineEmbeddedPickerView:(id)arg1 didSelectMediaAssetAttachments:(id)arg2 fromSource:(long long)arg3 currentPhotoAssetShown:(id)arg4;
-(void)storylineEmbeddedPickerView:(id)arg1 didSelectAssetWithID:(id)arg2 wasSelected:(BOOL)arg3 selectedMediaAttachments:(id)arg4;

@end

