/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:01:03 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSwizzle : NSObject {

	Class cls;
	SEL selector;
	SEL mangledSelector;
	/*function pointer*/void* originalIMP;
	/*function pointer*/void* swizzleIMP;
	unsigned long long ID;
	BOOL instance;

}
-(id)initWithClass:(Class)arg1 selector:(SEL)arg2 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
@end

