/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:51 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBTarotCardEntityProtocol.h>

@class NSString, NSURL;

@interface FBTarotInstantArticleCardEntity : NSObject <FBTarotCardEntityProtocol> {

	NSString* _articleID;
	NSURL* _shareURL;

}

@property (nonatomic,copy,readonly) NSString * articleID;                           //@synthesize articleID=_articleID - In the implementation block
@property (nonatomic,copy,readonly) NSURL * shareURL;                               //@synthesize shareURL=_shareURL - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) id<FBTarotCardMediaProtocol> cardMedia; 
@property (nonatomic,copy,readonly) NSString * cardType; 
@property (nonatomic,copy,readonly) NSString * cardID; 
-(id)initWithArticleID:(id)arg1 shareURL:(id)arg2 ;
-(NSString *)articleID;
-(id<FBTarotCardMediaProtocol>)cardMedia;
-(NSString *)cardID;
-(NSString *)cardType;
-(NSURL *)shareURL;
@end

