/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:56 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBNetworkerRequestDelegate.h>

@protocol FBHttpRequestToken, FBNetworkDispatch;
@class FBNetworkerRequest, NSString;

@interface FBThirdPartyAppAuthController : NSObject <FBNetworkerRequestDelegate> {

	/*^block*/id _successBlock;
	/*^block*/id _failureBlock;
	FBNetworkerRequest* _request;
	id<FBHttpRequestToken> _token;
	id<FBNetworkDispatch> _requesterConfiguration;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)networkerRequest:(id)arg1 didSucceed:(id)arg2 status:(id)arg3 ;
-(void)networkerRequest:(id)arg1 didFail:(id)arg2 status:(id)arg3 ;
-(id)initWithRequesterConfiguration:(id)arg1 ;
-(void)thirdPartyAppAuth:(id)arg1 successBlock:(/*^block*/id)arg2 failureBlock:(/*^block*/id)arg3 ;
-(void)dealloc;
@end

