/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/CKCompositeComponent.h>

@class FBFeedToolbox, FBMemTopicFeedPivotFeedUnit, NSString;

@interface FBTopicFeedUpsellFollowupComponent : CKCompositeComponent {

	FBFeedToolbox* _toolbox;
	FBMemTopicFeedPivotFeedUnit* _model;
	NSString* _storyId;

}

@property (nonatomic,readonly) FBFeedToolbox * toolbox;                          //@synthesize toolbox=_toolbox - In the implementation block
@property (nonatomic,readonly) FBMemTopicFeedPivotFeedUnit * model;              //@synthesize model=_model - In the implementation block
@property (nonatomic,copy,readonly) NSString * storyId;                          //@synthesize storyId=_storyId - In the implementation block
+(id)newWithUnit:(id)arg1 storyId:(id)arg2 toolbox:(id)arg3 ;
-(FBFeedToolbox *)toolbox;
-(void)didTapFooter:(id)arg1 ;
-(NSString *)storyId;
-(FBMemTopicFeedPivotFeedUnit *)model;
@end

