/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:38 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBMemComment, UIView;

@interface FBUFICommentSecondaryActionButtonTapContext : NSObject {

	FBMemComment* _comment;
	UIView* _actionButton;

}

@property (nonatomic,readonly) FBMemComment * comment;              //@synthesize comment=_comment - In the implementation block
@property (nonatomic,readonly) UIView * actionButton;               //@synthesize actionButton=_actionButton - In the implementation block
-(id)initWithComment:(id)arg1 actionButton:(id)arg2 ;
-(FBMemComment *)comment;
-(UIView *)actionButton;
@end

