/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:44 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface FBUFICustomButtonFeedCustomizationContext : NSObject {

	NSString* _title;
	unsigned long long _glyphName;
	NSString* _accessibilityIdentifier;
	/*^block*/id _actionBlock;

}

@property (nonatomic,copy,readonly) NSString * title;                                //@synthesize title=_title - In the implementation block
@property (nonatomic,readonly) unsigned long long glyphName;                         //@synthesize glyphName=_glyphName - In the implementation block
@property (nonatomic,copy,readonly) NSString * accessibilityIdentifier;              //@synthesize accessibilityIdentifier=_accessibilityIdentifier - In the implementation block
@property (nonatomic,copy,readonly) id actionBlock;                                  //@synthesize actionBlock=_actionBlock - In the implementation block
-(id)initWithTitle:(id)arg1 glyphName:(unsigned long long)arg2 accessibilityIdentifier:(id)arg3 actionBlock:(/*^block*/id)arg4 ;
-(unsigned long long)glyphName;
-(NSString *)title;
-(NSString *)accessibilityIdentifier;
-(id)actionBlock;
@end

