/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:44 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBUFICustomButtonFeedCustomization : NSObject {

	/*^block*/id _contextBlock;
	/*^block*/id _iconBlock;
	/*^block*/id _highlightedIconBlock;

}

@property (nonatomic,copy,readonly) id contextBlock;                      //@synthesize contextBlock=_contextBlock - In the implementation block
@property (nonatomic,copy,readonly) id iconBlock;                         //@synthesize iconBlock=_iconBlock - In the implementation block
@property (nonatomic,copy,readonly) id highlightedIconBlock;              //@synthesize highlightedIconBlock=_highlightedIconBlock - In the implementation block
-(id)contextBlock;
-(id)iconBlock;
-(id)highlightedIconBlock;
-(id)initWithContextBlock:(/*^block*/id)arg1 iconBlock:(/*^block*/id)arg2 highlightedIconBlock:(/*^block*/id)arg3 ;
@end

