/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:51 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface FBUIKitPath : NSObject <NSCopying> {

	CGPathRef _CGPath;

}

@property (nonatomic,readonly) CGPathRef CGPath;              //@synthesize CGPath=_CGPath - In the implementation block
-(id)initWithCGPath:(CGPathRef)arg1 ;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(CGPathRef)CGPath;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

