/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:30 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBVideoHomeDataSourceUpdatesListener.h>

@class FBVideoHomeDataSource, FBVideoHomeReactionModelTransformer, FBReactionContext, NSString;

@interface FBVideoHomeDataLivenessManager : NSObject <FBVideoHomeDataSourceUpdatesListener> {

	FBVideoHomeDataSource* _dataSource;
	FBVideoHomeReactionModelTransformer* _modelTransformer;
	FBReactionContext* _reactionContext;

}

@property (nonatomic,retain) FBReactionContext * reactionContext;              //@synthesize reactionContext=_reactionContext - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(FBReactionContext *)reactionContext;
-(void)videoHomeDataSource:(id)arg1 didUpdateStories:(id)arg2 ;
-(void)videoHomeDataSource:(id)arg1 didUpdateUnitModel:(id)arg2 ;
-(void)setReactionContext:(FBReactionContext *)arg1 ;
-(void)dealloc;
-(id)initWithDataSource:(id)arg1 ;
@end

