/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKComponentController.h>
#import <Facebook/FBComponentControllerWorkingRangeListenerProviding.h>
#import <Facebook/FBCommentIndicatorControllerDelegate.h>

@class FBStoryShareHandler, FBNuxStepChainController, FBCommentStreamCommentIndicatorController, NSString;

@interface FBVideoChannelPlaylistItemComponentController : CKComponentController <FBComponentControllerWorkingRangeListenerProviding, FBCommentIndicatorControllerDelegate> {

	FBStoryShareHandler* _shareHandler;
	FBNuxStepChainController* _tooltipController;
	BOOL _wasPlayingBeforePausedByApp;
	FBCommentStreamCommentIndicatorController* _commentIndicatorController;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)didMount;
-(void)willUnmount;
-(id)workingRangeListenerForComponent:(id)arg1 ;
-(void)_channelPlaylistItemCommentAction:(id)arg1 ;
-(void)hideTooltip;
-(void)_showCommentBubbleWithFocusFeedbackID:(id)arg1 composerActivationSource:(id)arg2 ;
-(void)didDismissCommentsBubble;
-(BOOL)commentIndicatorController:(id)arg1 shouldDisplayIndicatorWithType:(long long)arg2 ;
-(id)commentIndicatorControllerDisplayingView:(id)arg1 forIndicatorType:(long long)arg2 ;
-(CGRect)commentIndicatorControllerDisplayingFrame:(id)arg1 forIndicatorType:(long long)arg2 withIndicatorSize:(CGSize)arg3 ;
-(void)commentIndicatorController:(id)arg1 didTapOnIndicatorOfType:(long long)arg2 ;
-(void)channelPlaylistItemCountsAction;
-(void)channelPlaylistItemViewCountsAction:(id)arg1 ;
-(void)channelPlaylistItemLikeAction:(id)arg1 context:(id)arg2 ;
-(void)channelPlaylistItemShareAction:(id)arg1 context:(id)arg2 ;
-(void)channelPlaylistItemCommentAction:(id)arg1 context:(id)arg2 ;
-(void)_pause;
-(void)_resume;
@end

