/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:30 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBExperimentContext.h>

@class NSString;

@interface FBVideoHomeFollowVideosTextExperimentContext : FBExperimentContext {

	NSString* _followVideos;
	NSString* _notificationsOn;
	NSString* _notificationsOff;
	NSString* _following;
	long long _timeDelayToAppearInFeed;
	long long _notificationsUpsellTimeOutMs;

}

@property (nonatomic,copy) NSString * followVideos;                               //@synthesize followVideos=_followVideos - In the implementation block
@property (nonatomic,copy) NSString * notificationsOn;                            //@synthesize notificationsOn=_notificationsOn - In the implementation block
@property (nonatomic,copy) NSString * notificationsOff;                           //@synthesize notificationsOff=_notificationsOff - In the implementation block
@property (nonatomic,copy) NSString * following;                                  //@synthesize following=_following - In the implementation block
@property (assign,nonatomic) long long timeDelayToAppearInFeed;                   //@synthesize timeDelayToAppearInFeed=_timeDelayToAppearInFeed - In the implementation block
@property (assign,nonatomic) long long notificationsUpsellTimeOutMs;              //@synthesize notificationsUpsellTimeOutMs=_notificationsUpsellTimeOutMs - In the implementation block
+(id)universeName;
+(id)parameterConfigurations;
+(unsigned)mobileconfigConfigSpecifier;
+(id)configurationName;
-(void)logExposure;
-(NSString *)followVideos;
-(NSString *)notificationsOff;
-(NSString *)notificationsOn;
-(long long)notificationsUpsellTimeOutMs;
-(long long)timeDelayToAppearInFeed;
-(void)setFollowVideos:(NSString *)arg1 ;
-(void)setNotificationsOn:(NSString *)arg1 ;
-(void)setNotificationsOff:(NSString *)arg1 ;
-(void)setTimeDelayToAppearInFeed:(long long)arg1 ;
-(void)setNotificationsUpsellTimeOutMs:(long long)arg1 ;
-(void)setFollowing:(NSString *)arg1 ;
-(NSString *)following;
@end

