/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:01:00 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableDictionary;

@interface FBVideoEdits : NSObject <NSCopying> {

	NSMutableDictionary* _data;

}
+(id)editsFromVideoAssetEdits:(id)arg1 ;
-(void)addFilterWithName:(id)arg1 withParameters:(id)arg2 ;
-(void)addImageOverlayFilter:(id)arg1 ;
-(void)setMuteAudio:(BOOL)arg1 ;
-(void)addTrimRange:(SCD_Struct_FB101)arg1 ;
-(id)trimRanges;
-(id)videoProcessorConfig;
-(void)addTrimRange:(SCD_Struct_FB101)arg1 scaleToDuration:(SCD_Struct_FB100)arg2 ;
-(void)clearTrimRanges;
-(void)clearCropRectangle;
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(id)mutableCopy;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)filters;
-(void)setCropRectangle:(CGRect)arg1 ;
-(BOOL)isAudioMuted;
-(CGRect)cropRectangle;
-(void)clearFilters;
@end

