/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>

@interface FBVideoStoryWithFollowComponent : CKCompositeComponent
+(id)newWithVideoComponent:(id)arg1 story:(id)arg2 video:(id)arg3 publisherVideoChannel:(id)arg4 recommendationContext:(id)arg5 options:(FBVideoStoryWithFollowComponentOptions)arg6 didTapProfileImageAction:(CKTypedComponentAction<>)arg7 didTapVideoOwnerTitleAction:(CKTypedComponentAction<>)arg8 didTapVideoInfoAction:(CKTypedComponentAction<>)arg9 videoHomeSessionIDProvider:(/*^block*/id)arg10 stateToggledToBlock:(/*^block*/id)arg11 feedToolbox:(id)arg12 ;
@end

