/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:01:00 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/FBVideoBroadcastSession.h>

@protocol FBVideoBroadcastSessionDelegate;
@class NSString;

@interface FBVideoBroadcastSessionBase : NSObject <FBVideoBroadcastSession> {

	NSString* _broadcastID;
	shared_ptr<FB::Functional::PromiseEither<NSError *, NSArray<FBManagedFileURL *> *> >* _dvrFinishRecordingPromise;
	atomic<int> _readyToProcesssData;
	atomic<int> _connectionIsAlive;
	atomic<CMTime> _baseTimestamp;
	atomic<CMTime> _lastAudioSampleBufferPts;
	atomic<CMTime> _lastVideoSampleBufferPts;
	id<FBVideoBroadcastSessionDelegate> _delegate;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (__weak) id<FBVideoBroadcastSessionDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(SCD_Struct_FB100)convertDeviceTimestamp:(SCD_Struct_FB100)arg1 toStreamTimestampWithBaseTimestamp:(SCD_Struct_FB100)arg2 ;
-(void)swapVideoWidthAndHeightAfterOrientationChange;
-(BOOL)isReadyForStreaming;
-(void)setBaseTimestamp:(SCD_Struct_FB100)arg1 ;
-(void)processVideo:(opaqueCMSampleBufferRef)arg1 ;
-(void)processAudio:(opaqueCMSampleBufferRef)arg1 ;
-(BOOL)isConnectionAlive;
-(Class)videoEncoderClass;
-(SCD_Struct_FB100)lastRecordedAudioTimestamp;
-(void)onInterruption;
-(void)onInterruptionEnded;
-(id)initWithBroadcastID:(id)arg1 ;
-(id)newDiskRecorder;
-(void)broadcastSessionDidLoseConnection:(id)arg1 ;
-(void)broadcastSessionDidStart:(FBNetworkSpeedTestStatus)arg1 ;
-(void)broadcastSessionDidReconnectWithReason:(id)arg1 ;
-(void)broadcastSessionDidFail:(FBVideoBroadcastSessionLoggingInfo)arg1 ;
-(void)broadcastSessionDidFinish:(id)arg1 sendEndOfStreamError:(id)arg2 loggingInfo:(FBVideoBroadcastSessionLoggingInfo)arg3 ;
-(void)setAdaptiveBitrateConfig:(FBAdaptiveBitrateConfig*)arg1 ;
-(SCD_Struct_FB638)diskVideoRecorderConfig;
-(id)diskRecorder;
-(SCD_Struct_FB100)lastVideoSampleBufferPts;
-(BOOL)isConnectionAliveUnsafeCheck;
-(BOOL)isReadyToProcesssData;
-(SCD_Struct_FB100)lastAudioSampleBufferPts;
-(SCD_Struct_FB100)convertDeviceTimestampToStreamTimestamp:(SCD_Struct_FB100)arg1 ;
-(PromiseEither<NSError *, NSArray<FBManagedFileURL *> *>*)_finishDiskRecording:(id)arg1 ;
-(void)setDelegate:(id<FBVideoBroadcastSessionDelegate>)arg1 ;
-(id<FBVideoBroadcastSessionDelegate>)delegate;
-(void)stop;
-(void)start;
-(void)resume;
-(id)broadcastID;
-(FBVideoBroadcastSessionStats*)stats;
-(void)cameraWillChange;
-(void)cameraDidChange;
-(void)pause:(BOOL)arg1 ;
@end

