/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:01:00 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSDictionary, FBVideoConfig, FBAudioConfig, FBSegmentConfig;

@interface FBVideoTranscoderConfig : NSObject <NSCopying> {

	NSDictionary* _config;
	FBVideoConfig* _videoConfig;
	FBAudioConfig* _audioConfig;
	FBSegmentConfig* _segmentConfig;

}

@property (nonatomic,copy,readonly) FBVideoConfig * videoConfig;                  //@synthesize videoConfig=_videoConfig - In the implementation block
@property (nonatomic,copy,readonly) FBAudioConfig * audioConfig;                  //@synthesize audioConfig=_audioConfig - In the implementation block
@property (nonatomic,copy,readonly) FBSegmentConfig * segmentConfig;              //@synthesize segmentConfig=_segmentConfig - In the implementation block
-(FBVideoConfig *)videoConfig;
-(FBSegmentConfig *)segmentConfig;
-(FBAudioConfig *)audioConfig;
-(BOOL)isEqual:(id)arg1 ;
-(id)initWithDictionary:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

