/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:56 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBVideoUploadSessionLogger.h>
#import <Facebook/FBVideoSegmentUploadSessionLogger.h>

@class NSDictionary, NSString;

@interface FBVideoUploadLogger : NSObject <FBVideoUploadSessionLogger, FBVideoSegmentUploadSessionLogger> {

	NSDictionary* _extras;
	NSString* _moduleName;
	double _initRequestStartTime;
	double _transferRequestStartTime;
	double _postRequestStartTime;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_logEvent:(id)arg1 ;
-(void)logUploadInitStart;
-(void)logUploadInitDequeue;
-(void)logUploadTransferSuccess;
-(void)_logEvent:(id)arg1 error:(id)arg2 ;
-(void)_logEvent:(id)arg1 extras:(id)arg2 ;
-(id)initWithModuleName:(id)arg1 extras:(id)arg2 ;
-(void)logUploadChunkTransferStart;
-(void)logUploadChunkTransferDequeue;
-(void)logUploadChunkTransferSuccess;
-(void)logUploadChunkTransferFailure:(id)arg1 ;
-(void)logUploadPostStart;
-(void)logUploadTransferStartIfFirstSegment;
-(void)logUploadPostSuccess;
-(void)logUploadInitSuccess;
-(void)logUploadPostDequeue;
-(void)logUploadInitFailure:(id)arg1 ;
-(void)logUploadPostFailure:(id)arg1 ;
-(void)logUploadTransferFailure:(id)arg1 ;
-(void)_logEvent:(id)arg1 elapsedTime:(double)arg2 ;
-(void)_logEvent:(id)arg1 elapsedTime:(double)arg2 error:(id)arg3 ;
-(void)_logEvent:(id)arg1 elapsedTime:(double)arg2 extras:(id)arg3 ;
-(void)logUploadChunkTransferResponse;
@end

