/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UIView, UILabel, UIImageView, UIImage, UIButton;

@interface FBVideoChannelWnsNuxView : UIView {

	UIView* _contentView;
	UILabel* _promptLabel;
	UIImageView* _arrowView;
	UIImage* _arrowImage;
	UIButton* _closeButton;
	UIButton* _wnsButton;
	/*^block*/id _dismissBlock;
	/*^block*/id _enterWnsBlock;
	/*^block*/id _cancelBlock;

}

@property (nonatomic,retain) UIButton * closeButton;              //@synthesize closeButton=_closeButton - In the implementation block
@property (nonatomic,retain) UIButton * wnsButton;                //@synthesize wnsButton=_wnsButton - In the implementation block
@property (nonatomic,copy) id dismissBlock;                       //@synthesize dismissBlock=_dismissBlock - In the implementation block
@property (nonatomic,copy) id enterWnsBlock;                      //@synthesize enterWnsBlock=_enterWnsBlock - In the implementation block
@property (nonatomic,copy) id cancelBlock;                        //@synthesize cancelBlock=_cancelBlock - In the implementation block
-(UIButton *)wnsButton;
-(void)setDismissBlock:(id)arg1 ;
-(void)setEnterWnsBlock:(id)arg1 ;
-(id)initWithFontFoundry:(id)arg1 ;
-(void)setWnsButton:(UIButton *)arg1 ;
-(id)_getArrowImage;
-(id)dismissBlock;
-(id)enterWnsBlock;
-(void)layoutSubviews;
-(id)cancelBlock;
-(UIButton *)closeButton;
-(void)setCloseButton:(UIButton *)arg1 ;
-(void)setCancelBlock:(id)arg1 ;
@end

