/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>

@protocol FBVideoPlayerComponentContaining;
@class CKComponent;

@interface FBVideoWithProfileAndSecondaryActionComponent : CKCompositeComponent {

	CKComponent* _profileImageOrReplayButtonComponent;
	CKComponent*<FBVideoPlayerComponentContaining> _videoPlayerContainerComponent;
	long long _state;

}

@property (nonatomic,readonly) CKComponent*<FBVideoPlayerComponentContaining> videoPlayerContainerComponent;              //@synthesize videoPlayerContainerComponent=_videoPlayerContainerComponent - In the implementation block
@property (assign,nonatomic) long long state;                                                                             //@synthesize state=_state - In the implementation block
+(id)newWithVideoComponent:(id)arg1 story:(id)arg2 video:(id)arg3 showSecondaryActionButton:(BOOL)arg4 didTapProfileImageAction:(CKTypedComponentAction<>)arg5 toolbox:(id)arg6 ;
-(vector<CKComponentAnimation, std::__1::allocator<CKComponentAnimation> >*)animationsFromPreviousComponent:(id)arg1 ;
-(CKComponent*<FBVideoPlayerComponentContaining>)videoPlayerContainerComponent;
-(long long)state;
-(void)setState:(long long)arg1 ;
@end

