/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <UIKit/UIView.h>
#import <Facebook/FBVideoPluginView.h>

@protocol FBVideoChannelEntryPluginView, FBQueriedVideoChannelFieldsProtocol;
@class FBMemFeedStory, FBUserSession, NSString, UIView, FBVideoChannelPlaylistDownloader, FBMemModelObject, FBVideoPlaybackController;

@interface FBVideoChannelEntryPlugin : UIView <FBVideoPluginView> {

	long long _state;
	double _videoDuration;
	FBMemFeedStory* _videoParent;
	FBUserSession* _session;
	NSString* _videoId;
	NSString* _channelId;
	NSString* _caller;
	UIView*<FBVideoChannelEntryPluginView> _pluginView;
	FBVideoChannelPlaylistDownloader* _playlistDownloader;
	FBMemModelObject*<FBQueriedVideoChannelFieldsProtocol> _videoChannel;
	FBVideoPlaybackController* _videoController;
	CGRect _videoFrame;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) CGRect videoFrame;                                               //@synthesize videoFrame=_videoFrame - In the implementation block
@property (assign,nonatomic,__weak) FBVideoPlaybackController * videoController;              //@synthesize videoController=_videoController - In the implementation block
@property (nonatomic,readonly) unsigned long long visibilityOptions; 
-(void)videoPlaybackController:(id)arg1 didChangeVideoPlaybackItem:(id)arg2 ;
-(void)videoPlaybackControllerDidStartPlayback:(id)arg1 ;
-(void)videoPlaybackControllerDidFinishPlayback:(id)arg1 ;
-(void)videoPlaybackController:(id)arg1 didLoadVideoDuration:(double)arg2 ;
-(void)videoPlaybackController:(id)arg1 didUpdatePlaybackTime:(double)arg2 ;
-(CGRect)videoFrame;
-(void)setVideoFrame:(CGRect)arg1 ;
-(unsigned long long)visibilityOptions;
-(id)initWithFrame:(CGRect)arg1 pluginView:(id)arg2 session:(id)arg3 videoParent:(id)arg4 videoId:(id)arg5 channelId:(id)arg6 caller:(id)arg7 ;
-(void)_updatePlaybackState:(id)arg1 ;
-(void)_processDownloaderResponse:(id)arg1 ;
-(void)layoutSubviews;
-(FBVideoPlaybackController *)videoController;
-(void)setVideoController:(FBVideoPlaybackController *)arg1 ;
@end

