/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:50 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBExperimentContext.h>

@interface FBWebRTCVideoKeyFrameIntervalExperimentContext : FBExperimentContext {

	int _key_frame_interval_ms;
	int _codec;
	int __v;

}

@property (nonatomic,readonly) int key_frame_interval_ms;              //@synthesize key_frame_interval_ms=_key_frame_interval_ms - In the implementation block
@property (nonatomic,readonly) int codec;                              //@synthesize codec=_codec - In the implementation block
@property (nonatomic,readonly) int _v;                                 //@synthesize _v=__v - In the implementation block
+(id)universeName;
+(id)parameterConfigurations;
-(int)key_frame_interval_ms;
-(int)_v;
-(int)codec;
@end

