/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:51 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKComponentController.h>

@class FIGAnnouncingNetworkImageSpecifier, UIImage;

@interface FIGAnnouncingNetworkImageComponentController : CKComponentController {

	FIGAnnouncingNetworkImageSpecifier* _specifier;
	id _downloadHandle;
	UIImage* _image;

}

@property (nonatomic,retain) UIImage * image;              //@synthesize image=_image - In the implementation block
-(void)didMount;
-(void)didRemount;
-(id)_imageComponent;
-(void)componentDidAcquireView;
-(void)componentWillRelinquishView;
-(void)_startDownload;
-(void)_didDownloadImage:(CGImageRef)arg1 error:(id)arg2 ;
-(void)_sendDownloadAction;
-(void)setImage:(UIImage *)arg1 ;
-(void)dealloc;
-(UIImage *)image;
-(id)_imageView;
-(void)_updateContentsRect;
-(void)_updateSpecifier;
@end

