/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:30 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBExperimentContext.h>

@interface IosMessengerVideoUploadIndeterminateSpinnerExperimentContext : FBExperimentContext {

	BOOL _message_video_upload_progress_view_switching_should_show_indeterminate_spinner;
	double _message_video_upload_progress_view_switching_switch_to_indeterminate_spinner_time_in_seconds;

}

@property (assign,nonatomic) BOOL message_video_upload_progress_view_switching_should_show_indeterminate_spinner;                              //@synthesize message_video_upload_progress_view_switching_should_show_indeterminate_spinner=_message_video_upload_progress_view_switching_should_show_indeterminate_spinner - In the implementation block
@property (assign,nonatomic) double message_video_upload_progress_view_switching_switch_to_indeterminate_spinner_time_in_seconds;              //@synthesize message_video_upload_progress_view_switching_switch_to_indeterminate_spinner_time_in_seconds=_message_video_upload_progress_view_switching_switch_to_indeterminate_spinner_time_in_seconds - In the implementation block
+(id)universeName;
+(id)parameterConfigurations;
+(unsigned)mobileconfigConfigSpecifier;
+(id)configurationName;
-(void)logExposure;
-(BOOL)message_video_upload_progress_view_switching_should_show_indeterminate_spinner;
-(double)message_video_upload_progress_view_switching_switch_to_indeterminate_spinner_time_in_seconds;
-(void)setMessage_video_upload_progress_view_switching_should_show_indeterminate_spinner:(BOOL)arg1 ;
-(void)setMessage_video_upload_progress_view_switching_switch_to_indeterminate_spinner_time_in_seconds:(double)arg1 ;
@end

