/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:30 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBExperimentContext.h>

@interface IosSearchPostSetUniverseV55ExperimentContext : FBExperimentContext {

	long long _search_results_posts_set_tab_bar_content_insets;

}

@property (assign,nonatomic) long long search_results_posts_set_tab_bar_content_insets;              //@synthesize search_results_posts_set_tab_bar_content_insets=_search_results_posts_set_tab_bar_content_insets - In the implementation block
+(id)universeName;
+(id)parameterConfigurations;
+(unsigned)mobileconfigConfigSpecifier;
+(id)configurationName;
-(void)logExposure;
-(long long)search_results_posts_set_tab_bar_content_insets;
-(void)setSearch_results_posts_set_tab_bar_content_insets:(long long)arg1 ;
@end

