/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:50 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MNAirlineBoardingPassBubbleLocalizedLabelsQueryFragmentBuilder <FBFragmentModelBuilderProtocol>
@required
-(id)getResult;
-(id)setBoardingZoneLabel:(id)arg1;
-(id)setPassengerNamesLabel:(id)arg1;
-(id)setFlightTerminalLabel:(id)arg1;
-(id)setBoardingTimeLabel:(id)arg1;
-(id)setPassengerSeatLabel:(id)arg1;
-(id)setViewBoardingPassCtaLabel:(id)arg1;
-(id)setDepartureLabel:(id)arg1;
-(id)setFlightGateLabel:(id)arg1;
-(id)setFlightLabel:(id)arg1;

@end

