/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:46 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <UIKit/UIView.h>

@class MNPSAppointmentCreateDatePickerView, UILabel;

@interface MNBookingRequestsAdminRequestCreationDatePickerView : UIView {

	MNPSAppointmentCreateDatePickerView* _startDatePickerView;
	MNPSAppointmentCreateDatePickerView* _startTimePickerView;
	UILabel* _endTimeLabel;
	MNPSAppointmentCreateDatePickerView* _endTimePickerView;

}
-(id)initWithFrame:(CGRect)arg1 delegate:(id)arg2 ;
-(void)fb_addStartDatePickerViewWithDelegate:(id)arg1 ;
-(void)fb_addStartTimePickerViewWithDelegate:(id)arg1 ;
-(void)fb_addEndTimeLabel;
-(void)fb_addEndTimePickerViewWithDelegate:(id)arg1 ;
-(void)fb_tapGesture:(id)arg1 ;
-(id)startDatePickerView;
-(id)startTimePickerView;
-(id)endTimeLabel;
-(id)endTimePickerView;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
@end

