/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:46 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface MNBookingRequestsViewerContext : FBValueObject <NSCopying> {

	BOOL _actsAsPageAdmin;
	NSString* _otherParticipantId;
	NSString* _actorId;

}

@property (nonatomic,copy,readonly) NSString * otherParticipantId;              //@synthesize otherParticipantId=_otherParticipantId - In the implementation block
@property (nonatomic,copy,readonly) NSString * actorId;                         //@synthesize actorId=_actorId - In the implementation block
@property (nonatomic,readonly) BOOL actsAsPageAdmin;                            //@synthesize actsAsPageAdmin=_actsAsPageAdmin - In the implementation block
-(NSString *)actorId;
-(BOOL)actsAsPageAdmin;
-(id)initWithOtherParticipantId:(id)arg1 actorId:(id)arg2 actsAsPageAdmin:(BOOL)arg3 ;
-(NSString *)otherParticipantId;
@end

