/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:47 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBViewerContextClassProvidable.h>
#import <Facebook/MNCDNPhotoDownloadRunnerListening.h>

@protocol MNCDNAssetDownloading;
@class MNAdaptiveImageDownloader, MNAsyncOperationTracker, NSString;

@interface MNCDNPhotoDownloader : NSObject <FBViewerContextClassProvidable, MNCDNPhotoDownloadRunnerListening> {

	id<MNCDNAssetDownloading> _assetDownloader;
	MNAdaptiveImageDownloader* _adaptiveImageDownloader;
	MNAsyncOperationTracker* _asynOperationTracker;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithProviderMapData:(id)arg1 ;
-(id)initWithAssetDownloader:(id)arg1 adaptiveImageDownloader:(id)arg2 ;
-(void)photoRunnerDidFinishWithPhoto:(id)arg1 forPhotoDownloadRequest:(id)arg2 forDownloadId:(unsigned long long)arg3 isFinalResponse:(BOOL)arg4 ;
-(void)photoRunnerDidFailToDownloadPhotoWithError:(id)arg1 forPhotoDownloadRequest:(id)arg2 forDownloadId:(unsigned long long)arg3 ;
-(id)downloadPhotoForPhotoDownloadRequest:(id)arg1 ;
-(void)cancelDownloadForDownloadId:(id)arg1 ;
@end

