/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:47 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/ZRTariffedUxSentryDelegate.h>
#import <Facebook/FBClassProvidable.h>

@class FBMLocationUpdateRequestHandler, ZRTariffedUxSentry, NSString;

@interface MNLocationPickerLocationRequestHandler : NSObject <ZRTariffedUxSentryDelegate, FBClassProvidable> {

	FBMLocationUpdateRequestHandler* _locationUpdateRequestHandler;
	ZRTariffedUxSentry* _sentry;
	/*^block*/id _failureBlock;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithProviderMapData:(id)arg1 ;
-(void)nonZeroRatedSessionUxMayActivate:(id)arg1 ;
-(void)nonZeroRatedSessionDidFailToStart:(id)arg1 ;
-(void)nonZeroRatedSessionUxMustDeactivate:(id)arg1 ;
-(void)enterNonZeroRatedSessionWithSuccessBlock:(/*^block*/id)arg1 failureBlock:(/*^block*/id)arg2 ;
-(id)requestLocationWithPermissionGrantedBlock:(/*^block*/id)arg1 permissionDeniedBlock:(/*^block*/id)arg2 locationUpdateBlock:(/*^block*/id)arg3 requestFailureBlock:(/*^block*/id)arg4 ;
-(void)dealloc;
-(BOOL)cancelRequest:(id)arg1 ;
@end

