/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:46 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <UIKit/UIView.h>

@protocol MNPSAppointmentCreateDatePickerViewDelegate;
@class FBDateFormatter, UIView, UITextField, UILabel;

@interface MNPSAppointmentCreateDatePickerView : UIView {

	id<MNPSAppointmentCreateDatePickerViewDelegate> _delegate;
	FBDateFormatter* _dateFormatter;
	UIView* _dividerView;
	UITextField* _textField;
	UILabel* _titleLabel;

}
-(id)initWithFrame:(CGRect)arg1 delegate:(id)arg2 title:(id)arg3 placeholder:(id)arg4 datePickerMode:(long long)arg5 dateFormatter:(id)arg6 ;
-(void)setDefaultTextWithDate:(id)arg1 ;
-(void)fb_addTitleLabelWithTitle:(id)arg1 ;
-(void)fb_addTextFieldWithPlaceholder:(id)arg1 datePickerMode:(long long)arg2 ;
-(void)fb_addDividerView;
-(id)fb_datePicker;
-(void)fb_inputViewValueChanged:(id)arg1 ;
-(id)fb_date;
-(void)fb_inputAccessoryViewDone:(id)arg1 ;
-(id)fb_dateString;
-(void)setDate:(id)arg1 minimum:(BOOL)arg2 ;
-(void)setDate:(id)arg1 maximum:(BOOL)arg2 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setDate:(id)arg1 ;
-(void)setMinimumDate:(id)arg1 ;
-(void)setMaximumDate:(id)arg1 ;
-(void)clear;
-(void)focus;
@end

