/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:57 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/MQEffectData.h>

@class NSString;

@interface MQLocalEffectData : MQEffectData {

	NSString* _effectClassName;
	NSString* _imageName;
	NSString* _imageUrl;

}

@property (nonatomic,copy,readonly) NSString * effectClassName;              //@synthesize effectClassName=_effectClassName - In the implementation block
@property (nonatomic,copy,readonly) NSString * imageName;                    //@synthesize imageName=_imageName - In the implementation block
@property (nonatomic,copy,readonly) NSString * imageUrl;                     //@synthesize imageUrl=_imageUrl - In the implementation block
-(NSString *)imageUrl;
-(NSString *)effectClassName;
-(id)initWithDictionary:(id)arg1 ;
-(id)toDictionary;
-(NSString *)imageName;
@end

