/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:58 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/MQDataModel.h>
#import <Facebook/MSQFileResourceReferrer.h>
#import <Facebook/MQScriptModelProtocol.h>

@class NSString, MSQModelUndoablePrimitive;

@interface MQScriptModel : MQDataModel <MSQFileResourceReferrer, MQScriptModelProtocol> {

	MSQModelUndoablePrimitive* _scriptDataProperty;
	MSQModelUndoablePrimitive* _fileNameProperty;
	MSQModelUndoablePrimitive* _needsFaceTrackerProperty;
	BOOL _dataSynchronized;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy) NSString * scriptData; 
@property (nonatomic,copy) NSString * fileName; 
@property (assign,nonatomic) BOOL needsFaceTracker; 
-(void)addAttributes:(id)arg1 options:(id)arg2 ;
-(void)parseAttributes:(id)arg1 options:(id)arg2 ;
-(void)didMoveToParent;
-(id)serialize:(id)arg1 options:(id)arg2 ;
-(void)parse:(id)arg1 relations:(id)arg2 fileController:(id)arg3 options:(id)arg4 ;
-(void)synchronizeResourcesUsingFileController:(id)arg1 ;
-(void)writeResourcesUsingFileController:(id)arg1 ;
-(BOOL)needsFaceTracker;
-(void)addResourceFileNames:(id)arg1 ;
-(void)setScriptData:(NSString *)arg1 ;
-(NSString *)scriptData;
-(void)setNeedsFaceTracker:(BOOL)arg1 ;
-(void)_fileStateDidChange;
-(id)initWithContext:(id)arg1 ;
-(id)tagName;
-(NSString *)fileName;
-(void)setFileName:(NSString *)arg1 ;
@end

