/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:58 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MSQSubTextureModelProtocol <MSQTextureModelProtocol>
@property (assign,nonatomic) float frameX; 
@property (assign,nonatomic) float frameY; 
@property (assign,nonatomic) float frameWidth; 
@property (assign,nonatomic) float frameHeight; 
@required
-(float)frameX;
-(float)frameY;
-(float)frameHeight;
-(void)setFrameX:(float)arg1;
-(void)setFrameY:(float)arg1;
-(void)setFrameWidth:(float)arg1;
-(void)setFrameHeight:(float)arg1;
-(float)frameWidth;

@end

