/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:52 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/RCTCxxModule.h>

@interface RCTGraphQLService : RCTCxxModule {

	unique_ptr<facebook::mobile::graphstore::GraphSchema, std::__1::default_delete<facebook::mobile::graphstore::GraphSchema> >* _otaSchema;
	unique_ptr<facebook::mobile::graphstore::GraphSchema, std::__1::default_delete<facebook::mobile::graphstore::GraphSchema> >* _mergedSchema;

}
+(id)moduleName;
+(void)load;
-(id)initWithGraphQLService:(shared_ptr<facebook::graphql::GraphQLService>*)arg1 schema:(const GraphSchema*)arg2 otaSchema:(id)arg3 localeProvider:(const function<std::__1::basic_string<char> ()>*)arg4 ;
-(id)initWithGraphQLService:(shared_ptr<facebook::graphql::GraphQLService>*)arg1 schema:(const GraphSchema*)arg2 otaSchema:(id)arg3 ;
@end

