/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:01:01 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol RCTJavaScriptExecutor <RCTInvalidating,RCTBridgeModule>
@property (getter=isValid,nonatomic,readonly) BOOL valid; 
@required
-(void)executeBlockOnJavaScriptQueue:(/*^block*/id)arg1;
-(void)flushedQueue:(/*^block*/id)arg1;
-(void)callFunctionOnModule:(id)arg1 method:(id)arg2 arguments:(id)arg3 callback:(/*^block*/id)arg4;
-(void)invokeCallbackID:(id)arg1 arguments:(id)arg2 callback:(/*^block*/id)arg3;
-(void)executeApplicationScript:(id)arg1 sourceURL:(id)arg2 onComplete:(/*^block*/id)arg3;
-(void)injectJSONText:(id)arg1 asGlobalObjectNamed:(id)arg2 callback:(/*^block*/id)arg3;
-(void)executeAsyncBlockOnJavaScriptQueue:(/*^block*/id)arg1;
-(BOOL)isValid;
-(void)setUp;

@end

