/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:57 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSArray;

@interface SRLocalizedWithClauseResult : NSObject {

	NSString* _stringWithNames;
	NSArray* _nameRanges;

}

@property (nonatomic,copy,readonly) NSString * stringWithNames;              //@synthesize stringWithNames=_stringWithNames - In the implementation block
@property (nonatomic,copy,readonly) NSArray * nameRanges;                    //@synthesize nameRanges=_nameRanges - In the implementation block
-(NSString *)stringWithNames;
-(NSArray *)nameRanges;
-(id)initWithStringWithNames:(id)arg1 nameRanges:(id)arg2 ;
@end

