/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:57 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSAttributedString;

@interface SYNAttributedStringWithToken : NSObject {

	NSString* _token;
	NSAttributedString* _attributedString;

}

@property (nonatomic,copy,readonly) NSString * token;                                   //@synthesize token=_token - In the implementation block
@property (nonatomic,copy,readonly) NSAttributedString * attributedString;              //@synthesize attributedString=_attributedString - In the implementation block
-(id)initWithToken:(id)arg1 replacement:(id)arg2 ;
-(NSAttributedString *)attributedString;
-(NSString *)token;
@end

