/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 25, 2016 at 12:00:30 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/AA3BC77C-8F98-4654-B3F4-E47B12803336/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBExperimentContext.h>

@interface TODOFBEventsNativeBirthdayDashboardExperimentContext : FBExperimentContext {

	BOOL _hscrollPromptEnabled;
	BOOL _nativeEnabled;
	BOOL _singlePromptEnabled;
	BOOL _inlineComposerEnabled;

}

@property (assign,nonatomic) BOOL hscrollPromptEnabled;               //@synthesize hscrollPromptEnabled=_hscrollPromptEnabled - In the implementation block
@property (assign,nonatomic) BOOL nativeEnabled;                      //@synthesize nativeEnabled=_nativeEnabled - In the implementation block
@property (assign,nonatomic) BOOL singlePromptEnabled;                //@synthesize singlePromptEnabled=_singlePromptEnabled - In the implementation block
@property (assign,nonatomic) BOOL inlineComposerEnabled;              //@synthesize inlineComposerEnabled=_inlineComposerEnabled - In the implementation block
+(id)universeName;
+(id)parameterConfigurations;
+(unsigned)mobileconfigConfigSpecifier;
+(id)configurationName;
-(void)logExposure;
-(BOOL)nativeEnabled;
-(void)setNativeEnabled:(BOOL)arg1 ;
-(BOOL)hscrollPromptEnabled;
-(BOOL)inlineComposerEnabled;
-(BOOL)singlePromptEnabled;
-(void)setHscrollPromptEnabled:(BOOL)arg1 ;
-(void)setSinglePromptEnabled:(BOOL)arg1 ;
-(void)setInlineComposerEnabled:(BOOL)arg1 ;
@end

